### ISSUE TITLE
Let the user add subjects which are not in the college career schedule

### ISSUE THREAD

**Issue by joaquinfontela** [FdelMazo/FIUBA-Map#102]
Implement an interface where the user can add new subjects which are not in his career schedule. He simply has to let the system know how many credits does the subject sum to the total credits and which are the correlative subjects.

**Comment by joaquinfontela** [comment]
(Puse esto por acá porque en la página decía que preferías directamente que levantaramos un issue para las sugerencias).

**Comment by FdelMazo** [comment]
Hola @joaquinfontela ! Gracias por el issue.

Me das un poco más de contexto de la idea? Lo que querés es _ver_ en el mapa un nodo más, por algo en particular, o solo queres que los créditos te computen?

Si es lo segundo, es algo que ya esta hecho! En #29 lo implemente, por sugerencia de otro pibe. Básicamente, puse un botón (si, medio escondido, ya se ya se) en los créditos de las electivas para agregar materias extra (todo crédito fuera del plan computa en electivas, por lo que averigué).

Chusmeate esto! https://github.com/FdelMazo/FIUBA-Map/issues/29#issuecomment-808947233

**Comment by FdelMazo** [comment]
Seria un lio agregarla al grafo encima, por como esta codeado, y quedaria medio raro por lo que decis. Si se te ocurre alguna forma de emprolijar esas cosas (en el codigo son `materias optativas`), sea poniendo el boton en otro lado u otra cosa, acepto PRs!

Cierro el issue por ya resuelto
