### ISSUE TITLE
Codigo de materias

### ISSUE THREAD

**Issue by mpata2000** [FdelMazo/FIUBA-Map#103]
## Mostrar Codigo de las Materias

Mostrar el codigo de cada materia cuando se hace hover sobre ella ademas de mostrar la cantidad de creditos

![Imgur](https://i.imgur.com/VORkYtM.png)

**Comment by FdelMazo** [comment]
Me encanta, después de las vacaciones lo agrego. Algo como... `[codigo] materia \n otorga n creditos`

**Comment by FdelMazo** [comment]
Debería ser solo modificar el atributo `title` de los nodos. Si queres mandarte y probar hacerlo @mpata2000 , bienvenido!

https://github.com/FdelMazo/FIUBA-Map/blob/ff667f1b3517a5e462b7d2ae7118acd948f0cad5/src/Node.js#L20-L26

**Comment by mpata2000** [comment]
Estoy medio que en la misma de tratar de descansar los pocos dias que tenemos, maybe si me inspiro lo hago pero no toque nunca js

**Comment by FdelMazo** [comment]
Solucionado en #109 

Genia total @AldanaRastrelli
