### ISSUE TITLE
Mostrar que se puede pedir materia por equivalencia

### ISSUE THREAD

**Issue by mpata2000** [FdelMazo/FIUBA-Map#104]
## Equivalencias

Asignar un cartel o un color especifico a las materias que se pueden pedir por equivalencia

 - Materias con el mismo codigo (Supongo que son las misma y se puede pedir)
 - Materias que son equivalentes
   -  [Ejemplo](https://sites.google.com/fi.uba.ar/ccii/principal/equivalencias-y-cr%C3%A9ditos?authuser=0)

---

Esto no se si seria un feature muy fácil de implementar y que le sirva muchos, pero estaría buen para los que estamos haciendo simultaneidad de dos carreras o alguno que esta pensando en hacerlo

**Comment by FdelMazo** [comment]
La verdad me parece in-implementable esto (gracias @mpata2000 por todas las ideas que vas tirando, sos una máquina). Vi tantos posts en fiuba consultas acerca de que equivalencia dan y que equivalencia no, y en particular sabiendo que es un proceso no automatico... y que la fuente es un google docs que parece bastante volatil..

No me siento comodo agregandolo, siento que es muy facil de errar y mostrarle al usuario algo que no es. Prefiero que cada uno averigue por su cuenta, y cuando aprueba, simplemente la aprueba con la E de eqvuialencia que ya existe en la app

**Comment by mpata2000** [comment]
Si me imagine por algo deje el comentario de abajo, ojala metan algo automático con un estándar mas fácil de seguir (plan2020?) sino esta para cerrar el issue. Nada se me ocurrio tirar las ideas para sumar buenos first issues a un proyecto enserio

**Comment by FdelMazo** [comment]
Gracias por las ideas!! Cierro este, pero sigamos con las otras! Todo lo que se te ocurra abrilooo
