### ISSUE TITLE
Exportar materias a Fiuba-Plan

### ISSUE THREAD

**Issue by mpata2000** [FdelMazo/FIUBA-Map#107]
# Exportar materias a Fiuba-Plan

Estaría bueno poder pasar materias que queres cursar  y/o  podes cursar a Fiuba Plan directo desde Fiuba Map. Creo que seria una forma mas visual de organizar la cursada de un cuatri y te ahorras el trabajo de ir buscando materia por materia en Fiuba Plan.

## Implementación

Tiro las opciones que se me ocurrieron:

- Tener un nuevo estado para la materia que sea *Cursar*/*Cursando* y que al apretar un botón se abra Fiuba Plan en una nueva pestaña con las materias cargadas.
- Apretar un botón que te deje seleccionar materias y se pasen a Fiuba Plan.
- Pasar todas la materias en naranja de las carreras que se están cursando.

Otro detalle a ver es que Fiuba Plan guarda las materias seleccionadas, entonces se tendría que ver si es mejor que cuando se exporten las materias se:

- Agregan a las que ya estaban 
- Limpia todo  queda solo las materias exportadas.

**Comment by FdelMazo** [comment]
Si, alguna integracion entre fiuba map <-> fiuba plan siempre quise hacer, pero nunca se exactamente __cual__ es la correcta para no pecar de agregar muchas boludeces a las apps. Lo que propones me gusta, pero tengo que seguir iterando lo que menos joda al usuario.

El mayor problema es que tal vez le agregas bocha de ruido al usuario, al pedo, porque el fiuba plan es algo que entras solo una vez cada 6 meses, pedirle que cliquee 4 materias para organizar horarios es una pavada. si de la nada le estas pidiendo padron, sincronizando contra el fiuba map, etc, pasa a ser un bodrio.

--- 

> Tener un nuevo estado para la materia que sea Cursar/Cursando y que al apretar un botón se abra Fiuba Plan en una nueva pestaña con las materias cargadas.

Esto ya existe, esta en el fiuba map abajo de 'Más Opciones' cuando cliqueas una materia. Estaria bueno que te aparezca directamente en el fiuba plan esas materias.

**Comment by mpata2000** [comment]
Tal vez se puede pensar al revez.

Desde Fiuba Plan tener un botón donde pongas un padrón o ya este cargado como usuario y pase las materias en "Cursando". Maybe ahi te ahorras eso de que se esten cambiando constantemente algo que se usa solo cada 6 meses. Pero se que es un problema muy *primer mundista*

**Comment by FdelMazo** [comment]
True. Me gusta mas pensarlo asi! Vamos refinando el feature

**Comment by FdelMazo** [comment]
Voy a cajonear esto hasta que resurja de nuevo, que hay otros issues mas importantes en los que laburar. Gracias @mpata2000 !
