### ISSUE TITLE
Falta "Asignatura Humanística Electiva" en Ingeniería Industrial

### ISSUE THREAD

**Issue by milagroscabeza** [FdelMazo/FIUBA-Map#11]
Falta la materia "Asignatura Humanística Electiva", cuya correlativa es 92.03 (Introducción a la Ingeniería Industrial), no tiene código porque se puede elegir entre 10 materias, pero es de 4 créditos y hay que hacerla sí o sí; en el plan aparece en el duodécimo cuatrimestre.

**Comment by FdelMazo** [comment]
Gracias! Ya agregada en da5461965313836c096cb2ce38d73801b7e0b878
