### ISSUE TITLE
Correlatividad Errónea

### ISSUE THREAD

**Issue by MathiWelz** [FdelMazo/FIUBA-Map#110]
La materia 75.29 - Teoría de Algoritmos I : Falta de correlatividad 61.07 Matemática Discreta. 
Solo tiene como correlativa 75.41 Algos 2.
Saludos. Increible trabajo

**Comment by FdelMazo** [comment]
En informatica eso cambio con la actualizacion del plan que ya es vigente! TDA ahora solo tiene a algo2 de correlativa. 

Aca podes ver todos los cambios del plan: http://www.fi.uba.ar/sites/default/files/DETALLE%20ACTUALIZACI%C3%93N%20PLAN%20ING.%20EN%20INFORM%C3%81TICA.pdf

Si se me paso algo por alto, avisa! Gracias por levantar el issue!
