### ISSUE TITLE
Scrollbars erráticas al hacer hover sobre el botón de "Plan de estudio"

### ISSUE THREAD

**Issue by Achus619** [FdelMazo/FIUBA-Map#113]
https://user-images.githubusercontent.com/20907887/135324991-7aec2dbf-245a-44cf-ab7b-d74981f2bac8.mov

Al acercar el cursor aparece una scrollbar lateral y otra abajo.
Al mover el cursor un poquito a la derecha del ícono, las barras empiezan a bailar 😂

Probado en Vivaldi v4.2.2406.52 (Chronium based), MacOS 11.6. La resolución del video es, no sé, un poquito menos que la nativa de la Mac? Pero originalmente me pasó en un monitor externo a 1440p

Saludos muy buena la radio

**Comment by FdelMazo** [comment]
No te merezco Achus. Gracias. Lo chusmeo

**Comment by FdelMazo** [comment]
Fixeado en 77046ae0716af925d72f4adf2f2f64ef62c8aae0

Gracias @Achus619 !
