### ISSUE TITLE
Agregar materias que están fuera del plan "oficial"

### ISSUE THREAD

**Issue by jtei99** [FdelMazo/FIUBA-Map#116]
Podrían agregar poder incluir en el mapa alguna materia que es electiva pero todavía no está en el plan (en mecánica hay varias) o que son materias de otras carreras que nos dan la equivalencia automáticamente. Y poder ponerle las correlativas manualmente nosotros.

**Comment by FdelMazo** [comment]
Hola @jtei99 !

Te fijas si lo que implemente en #29 te sirve y se adapta a tu caso de uso? También me interesa saber de esto: 

> materia que es electiva pero todavía no está en el plan

Agregaron materias en mecanica que no estan en el pdf? Hubo algun comunicado? Tienen correlativas y todo? así las agrego a mano!

**Comment by jtei99** [comment]
Buenas! No agregaron oficialmente aún, pero en teoría este cuatrimestre agregan algunas, y además hay varias que ya dan los créditos de forma automática, porque son cursos que se van a transformar en electivas.

**Comment by FdelMazo** [comment]
Joya! Creo que con el feature de agregar materias optativas deberías estar cubierto
