### ISSUE TITLE
Créditos fuera del plan no contabilizados para la tesis

### ISSUE THREAD

**Issue by Lukas-De-Angelis-Riva** [FdelMazo/FIUBA-Map#118]
Hola! Básicamente sucede esto:
![image](https://user-images.githubusercontent.com/60785752/147678138-0459f288-66a3-4075-aea8-e9594a20f24d.png)
No sólo sucede en el borde (con 4), aún poniendo 5, 6 o muchos créditos no se habilita.

Intercambiando los 4 créditos por fuera del plan con 4 créditos dentro del plan (por ejemplo por taller 2) sí se habilita.

**Comment by FdelMazo** [comment]
Uffff, que caso tan borde. Gracias por encontrarlo! Lo soluciono en un ratito

**Comment by FdelMazo** [comment]
Fixeado en d49fdacd0385c9e992534c54352c4a69b7f51189

En 2 minutines deberia estar deployado!
