### ISSUE TITLE
Vista considerando grupos de materias a cursar por cuatrimestre

### ISSUE THREAD

**Issue by JDSanto** [FdelMazo/FIUBA-Map#120]
Las materias del mapa están agrupadas en columnas. Actualmente, las obligatorias están agrupadas y ordenadas por cuatrimestre según el plan de estudio (y las electivas están por allá).

Con la funcionalidad de "voy a cursar las materias XYZ en 1, 2, 3 cuatrimestres", se podría agregar una vista alternativa donde cada columna tenga las materias a cursar en un mismo cuatrimestre, determinado por el plan del usuario. El botón de la vista podría estar en el dropdown de configuración o como otro abajo a la derecha.

Sería algo así, solo que con colores menos feos.

![image](https://user-images.githubusercontent.com/4763786/155860064-668dcb71-47c5-4a75-89c5-315c64cce779.png)

Algunas cosas a considerar/pensar/etc.
- La información de "materias a cursar" se puede combinar con la agrupación del plan original si el usuario no especificó los cuatrimestres para algunas materias, por ejemplo las que ya aprobó.
  - O solo mostrar las que tienen cuatrimestre asignado.
- Tirar la noción de "dentro de 3 cuatris", y cambiarlo por "voy a cursar esto el cuatri 2023c2, cursé esto en el 2021c1".

**Comment by FdelMazo** [comment]
> JDSanto assigned FdelMazo

...

**Comment by FdelMazo** [comment]
Okey, entiendo la idea y me encanta. Creo que se me ocurre una cosa arriba:

> Tirar la noción de "dentro de 3 cuatris", y cambiarlo por "voy a cursar esto el cuatri 2023c2, cursé esto en el 2021c1".

Ya que vamos a implementar nocion de que cuatri se va a cursar, no te parece copado agregarlo para __todo__ ? O sea, en vez de ordenar las materias futuras, ordenar todo mi plan de cursadas. Es un agregado trivial, y siento que es lindo para los dementes con TOC que quieren ver su historial de cursada entero

**Comment by JDSanto** [comment]
> Ya que vamos a implementar nocion de que cuatri se va a cursar, no te parece copado agregarlo para todo ? O sea, en vez de ordenar las materias futuras, ordenar todo mi plan de cursadas.

Qué pasaría con la gente que solo piensa _un_ cuatri adelante? Ahí te queda un plan incompleto, salvo que le pongas un valor por defecto, y eso trae el problema de que cambiar todo porque te falta una correlativa implicaría arrastrar todo el plan de materias a mano.

En mis ojos (no sé qué tan fácil sería implementar esto porque desconozco graph-viz) existirían cuatro "grupos" generales: las materias aprobadas, las materias a cursar (incluyendo electivas), las materias sin cuatrimestre asignado (agrupada por como dice el plan, para encontrarlas fácil) y por último las electivas. Es muy similar a lo que hay actualmente implementado solo que le clavás las próximas materias en el medio, de las materias obligatorias.

```
CBC --> Materias --> Materias -->         Materias sin categorizar        --> Materias electivas sin categorizar
        Aprobadas    Próximas     (tal como está en el plan de la carrera)        (tal como está ahora)
```

**Comment by FdelMazo** [comment]
Matemos la idea de dos vistas. Hagamos esto y que sea el default para todos.

En grandes rasgos, quedaría el orden:

`[ Aprobadas sin Cuatri] -> [Materias con cuatri] -> [Materias sin cuatri obligatorias] -> [Materias sin cuatri electivas]`

Si, dije exactamente lo que dijiste en tu comentario anterior.
