### ISSUE TITLE
No se guarda la cantidad de aplazos del usuario

### ISSUE THREAD

**Issue by JDSanto** [FdelMazo/FIUBA-Map#122]
Es un número que causa tristeza pero debería persistirse

![image](https://user-images.githubusercontent.com/4763786/156566989-d775beef-ed89-4ab4-b0a4-0206b7e95b9d.png)

**Comment by FdelMazo** [comment]
> JDSanto assigned FdelMazo

...

**Comment by FdelMazo** [comment]
Es una pavada de hacer, espero con ansias tu PR
