### ISSUE TITLE
Bug visual al activar y desactivar el boton de "materias electivas"

### ISSUE THREAD

**Issue by salluzziluca** [FdelMazo/FIUBA-Map#127]
(primero que nada, mil gracias por las cosas que haces, tanto el organizador como el plan son increibles y ayudan una banda, sos un genio Fede). 

El bug en si es puramente visual y no jode en nada, pero lo pongo aca por las dudas. Al activar y luego desactivar el boton de "materias electivas" ocurre lo siguiente

![image](https://user-images.githubusercontent.com/63552496/165522250-dcc4e965-4f3b-48d5-8eac-a963957f0b02.png)
Entiendo que deben ser las flechas que antes los unican con las materias electivas que desaparecen de la no-mejor-forma jajajaja

**Comment by FdelMazo** [comment]
Gracias @salluzziluca (por las palabras y por levantar el bug)! Te saldrá de casualidad grabar la pantalla y mostrar el bug de punta a punta? Así veo si estas loggeado, en que carrera es, si clickeas rapido o no el boton de electivas, etc.

Digo porque este bug es algo que muy de vez en cuando me cruzo, pero nunca me sale reproducirlo!

Si después de tener esas mil flechitas clickeas en algun lado, desaparecen?

**Comment by salluzziluca** [comment]
Ahi te grabo, apenas pasas el mouse por encima de alguna materia se va. Cuando el hover activa las flechas propias de cada materia se reordenan las otras

**Comment by salluzziluca** [comment]
Tuki, aca te grabé un(https://youtu.be/xpvYcm41m8s)[video], avisame si queres ver algo más. Por lo que veo me pasa con "todas" las carreras (no probé un a una). Cada vez que toco alguna de las opciones de agregar materias y la saco, quedan las flechas bugeadas.

**Comment by FdelMazo** [comment]
Gracias por el video Luca!! En estos días lo reviso!
