### ISSUE TITLE
Revisar las materias que requieren creditos

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Map#128]
Plan de informatica:

> Cuando se piden créditos aprobados para cursar una asignatura, estos incluyen a los 38 del CBC

La verdad que a esta altura no estoy seguro si toooodas las carreras tienen eso y cuentan los del CBC, o si solo algunas. Habria que ir una por una fijandose. Y suponiendo que sí... pones los 38 creditos iniciales a todos los usuarios? los diferencias de alguna manera? Tal vez puede ser una barrita nueva (verde?) de progreso el CBC, no es mala idea. Se lo das por aprobado a todo el mundo por default y de ultima se puede sacar?

(aprovechar y sacar el 'ver cbc entero' del tooltip del cbc...)
(y ponerle flechita al tooltip del link al plan de estudios, y hacer que el tooltip de la cantidad de materias aprbadas sea igual al resto)

**Comment by FdelMazo** [comment]
Solucionado en 5d68782965fe4aabf51e2d37b2b02e9d38f1f434

@TomasArrachea si estas en algun momento libre, podrías confirmar que esta andando bien todo el tema de los creditos? me hago un choclo de que requiere que y tengo miedo de haberme confundido en cosas

**Comment by TomasArrachea** [comment]
Hola @FdelMazo! Me parece que hay algún error con el cálculo. Para las materias que requieren créditos está pidiendo 30 más de lo que debería. Por ejemplo, para cursar Estructura de las Organizaciones se requieren 60 créditos pero aparece disponible recién al llegar a 90 créditos. 
Por otro lado, en mi opinión siento que el hecho de que el contador de créditos sume también los del cbc hace un poco confuso saber cuando se llega a los mínimos, Yo dejaría el contador como antes, pero a la hora de chequear los créditos necesarios restaría los 38 del cbc y listo. Espero que se entienda eso ultimo, sino puedo intentar hacer un PR cuando tenga un poco de tiempo!

**Comment by TomasArrachea** [comment]
No me deja cerrar el issue porque no lo creé yo, pero ahí está funcionando perfecto!

**Comment by FdelMazo** [comment]
Reabro esto porque me siguen llegando mensajes de que esta mal lo que esta en el fmap:

> Hola!! En Ing. Civil el TPP son 200 créditos sin contar CBC. Osea tendrían que ser 238 en el fiuba map

Pero no estoy nada seguro de estas cosas. Las fuentes son siempre super dudosas. Creo que lo mejor sería agregar un flag para que diga `N creditos (con CBC)` (asi al menos el usuario tiene claro que quedo contabilizado), y tambien un flag para solicitar ayuda de cada carrera

**Comment by FdelMazo** [comment]
929bf4978f87dd5a0a8e75c565883d0ad4f5308d
