### ISSUE TITLE
Falta el Trabajo Profesional de Sistemas

### ISSUE THREAD

**Issue by tomasaccini** [FdelMazo/FIUBA-Map#13]
En sistemas tenes Trabajo Profesional obligatorio con las correlativas 95.24, 95.59 y 95.60

**Comment by tomasaccini** [comment]
Da 12 creditos cuando lo aprobas, cuando marcas todas las obligatorias como aprobadas suma 136 créditos y para recibirte son 148 :)

**Comment by FdelMazo** [comment]
Agregado en 5ce5e6f0e6ac074b99f69e512915fe720e935bde !
Le baje a  que necesitas 136 para obligatorias, y despues un progressbar de 12 del tpp, para que quede más lindo (por más que se escape del pdf oficial)
