### ISSUE TITLE
Creditos extracurriculares

### ISSUE THREAD

**Issue by matias-gonz** [FdelMazo/FIUBA-Map#134]
Alguna materia para poner creditos extracurriculares?

**Comment by FdelMazo** [comment]
Hola @matias-gonz !

Esa idea la implementé en #29. Fijate si te sirve, y si se te ocurre algun lugar menos escondido para meter el feature, te acepto la idea!

**Comment by matias-gonz** [comment]
No lo habia visto! :man_facepalming:
Gracias fede!
