### ISSUE TITLE
Algun favicon lindo?

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Map#139]
Para fiuba repos, map, plan

**Comment by Maleriandro** [comment]
Intenté hacer un favicon para fiubamap. Es más que nada una idea para que capaz alguien que sepa de diseño gráfico pueda mejorar. La idea que se me ocurrió es 2 materias conectadas por una flecha, y para darle mas variedad, que ambas materias esten en distintos "estados", en este caso una aprobada y la otra lista para cursar. Los nombres de las materias son placeholders porque en 32x32 ni se lee lo que dice.
![Full Res](https://user-images.githubusercontent.com/41594090/185017569-aa2d8521-526f-40fc-b11c-b15699fe7dfc.png)


Esta es la version escalada a 32x32 (el tamaño de los favicons) y la edite un poco para que se vea apenas mejor, pero es practicamente la de arriba escalada.
![32x32](https://user-images.githubusercontent.com/41594090/185017604-cad62cd4-57b0-4f12-88a4-8d8acca0e259.png)

**Comment by FdelMazo** [comment]
Mil mil mil gracias @Maleriandro ! La idea me encanta, es verdad que el favicon tiene que ser lo más mínimo posible, para evitar que no se entienda nada. Una materia conectada a otra, o a dos, va re bien para el FIUBA-Map.

No se bien que hacer... Es al pedo un favicon la verdad, pero se siente lindo que no sea el icono de github de siempre. Estaba pensando armarme algun favicon para mis proyectos de FIUBA y poder usar eso genéricamente en todo lo que tengo, en vez de tener que ir haciendo uno por cada proyecto. Tal vez algo con las columnas de fiuba, o algo con el logo de fiuba, o un mix del logo de github con la cara de fiuba... no lo se!

**Comment by FdelMazo** [comment]
Por ejemplo. Fusionar la carita negra de github con la carita negra de fiuba!

![image](https://user-images.githubusercontent.com/25667102/185103746-2e8dd1ac-9b8f-48cc-8686-148d93a6af42.png)
![image](https://user-images.githubusercontent.com/25667102/185103801-c3eda010-4e2e-4c04-9b5d-c5a5f61f51ed.png)

**Comment by Maleriandro** [comment]
![logofiuba](https://user-images.githubusercontent.com/41594090/185223599-34e32ea1-6735-4086-8578-002e770fe7c2.png)
Se podría usar el logo circular de fiuba (el mismo que en fi.uba.ar) pero en color negro, pero me parece que cuando se escala a 32x32 no queda demasiado claro que es el icono. Intenté combinarlo con el de github, pero al achicar la parte de la cara, queda todavía menos claro que es.
![logofiuba_github](https://user-images.githubusercontent.com/41594090/185229770-6bc6f76c-199d-425f-ab95-252e5bdebfd6.png)

**Comment by FdelMazo** [comment]
Gracias por las imagenes @Maleriandro !

Las probé y no me convencieron que tengan taaanto detalle, en browsers desde el cel no me convencian tanto.

Terminé agregando una que me pareció más sencilla

 ![](https://raw.githubusercontent.com/FdelMazo/FIUBA-Map/master/public/favicon.png)
