### ISSUE TITLE
El boton al lado del pradrón no se entiende mucho para qué es

### ISSUE THREAD

**Issue by tomasaccini** [FdelMazo/FIUBA-Map#14]
Capaz se podría agregar un tooltip cuando pasas el mouse por arriba para explicar qué hace o cambiar el icono por uno clasico de save, me costo entender que era para guardar.
![image](https://user-images.githubusercontent.com/22566107/108906652-e12f0f00-75ff-11eb-841b-55afb89a0e04.png)

**Comment by FdelMazo** [comment]
Agregué un `ingresar` en 10ee481b7b3dc0f56f2c59ff5ba84fa57a431a37
