### ISSUE TITLE
Filtro por Créditos

### ISSUE THREAD

**Issue by gcc-cdimatteo** [FdelMazo/FIUBA-Map#141]
Buenas :) Creo que estaría muy bueno tener un filtro por cantidad de créditos. Muchas veces busco materias para completar la cantidad de créditos que quiero meter y lo hago manual, me parece que sería muy útil esa funcionalidad :D

**Comment by FdelMazo** [comment]
Me gustaaa. No se como poder agregar mas filtros sin que se haga un choclo de UX la app (por mi, mientras menos botones, mejor). Estaba pensando hace bastante que tal vez puedo diferenciar de alguna forma (sutil) las materias de 6 créditos que de las de 4. Por ejemplo, tamaño del borde, o boldness de la font, o incluso tamaño del nodo... 

O sea, algo que no me gusta es que todo quede enteramente explicito. Si puedo comunicar algo de manera visual, mejor!

Si se te ocurren ideas, ponele, viendo los ejemplos de 'node styles' de la lib que usa el fmap, las acepto! https://visjs.github.io/vis-network/examples/

 Y tambien siempre acepto ideas en forma de PRs :)

**Comment by gcc-cdimatteo** [comment]
Tenes razón en lo que decís de cuantos menos botones mejor, y ya que mencionas lo de “diferenciar de alguna forma sutil” se me ocurrió quizás que el formato del texto del nombre de las materias tenga un incremento de negrita proporcional a la cantidad de créditos que superen el default, que podría ser 4. Porque tener un estilo distinto de cuadrito sería tener uno por cada cantidad de créditos única y quizás es un embrollo.
Lo del nodo me parece re lindo también. Quizás ahí, implementar un nodo por cada cantidad única de créditos no sería tan complicado 🤔

**Comment by FdelMazo** [comment]
Creo que habría que fijarse las cantidades de créditos que se pueden dar en materias, porque la mayor diferencia que importa es la de 4 y 6 créditos. Con boldness debería quedar bien, o tal vez solamente si podemos hacer que se orden de mayor a menor, cosas asi.

**Comment by FdelMazo** [comment]
@nazar9318 me parece un poco verboso eso y lo quiero evitar! Ya de por si, al pararte con el mouse en una materia, te dice cuantos créditos otorga. Quiero que, visualmente, el mapa tenga la información justa y necesaria! Por esto estoy buscando alguna manera visual, no textual, de transmitir la cantidad de creditos de cada materia

**Comment by FdelMazo** [comment]
No es ideal, no es perfecto, pero agregué que, si se puede, se ordenen las materias por creditos, de mayor a menor. O sea que si abris las electivas, y te aparecen mil electivas, al menos sabes que 'las del fondo' son las de menos creditos

9e839695b1605b3c45ae9284dde0160659ef08d6

Lo agregué porque es un cambio super trivial y que no cambia mucho, pero no siento que cierre el issue del todo.

**Comment by FdelMazo** [comment]
En hover ahora se ve de manera mas linda la cantidad de creditos. Qué opinan, @nazar9318 @gcc-cdimatteo? Metanse a la pagina y prueben un toque jugar con el mouse, a ver si ahora es mas sencillo discriminar las electivas de 6 o de 4 creditos!


![2022-09-27_15-26](https://user-images.githubusercontent.com/25667102/192607736-36ce4e96-104e-4274-9498-fa2fa65719b0.png)

**Comment by gcc-cdimatteo** [comment]
Disculpa @FdelMazo, recién puedo ver esto.

Me gusta cómo quedó, no veo para nada lenta la página :)

Le sigo dando vueltas a dónde se podría poner el filtro por créditos...

¿Quizás un _widget_ arriba de **Materias Electivas** o a lo último de las orientaciones, tipo ComboBox o con flechitas en los extremos para seleccionar la cantidad de créditos?

No sé, por ahí estoy flasheando. Se me acaba de ocurrir :p

**Comment by FdelMazo** [comment]
Eeeee no estaría mal! Un cosito que en hover de las materias electivas te deje prender solo las de 4/6 creditos (bah, que se adapte a lo que hay). Se re puede armar! Pero estoy un toque sin tiempo... 

Ahora que el código esta más lindo no debería ser taaaaan complejo de armar. Te bancas intentar, y mandarme algun PR? :)

(o quien sea que tenga ganas de mandarse)

**Comment by gcc-cdimatteo** [comment]
Obvio, re :) 

Cuando tenga un ratito libre puedo ver de ponerme con eso y te cuento :)

**Comment by FdelMazo** [comment]
Cierro este issue. Agregar filtrado a la app es muy complejo, y me parece que no va a dar tanto rédito como creemos. La carrera con más quilombo de electivas es ing informática, y ahora con el plan nuevo la cantidad de electivas se va a bajar muchísimo. El problema de no estar seguro que materias hacer se va a ver bastante solucionado estructuralmente, y no creo que el fmap tenga que meterse en el medio.
