### ISSUE TITLE
Deseleccionar materia no devuelve menú superior principal

### ISSUE THREAD

**Issue by Maleriandro** [FdelMazo/FIUBA-Map#142]
Al seleccionar una materia, se mantiene la barra de edición de la materia, aún luego de deseleccionar la materia. Al seleccionar otra materia cambia la barra de edición a dicha otra materia, pero no se puede volver al menú principal para, por ejemplo, guardar las ediciones que se hicieron.

**Comment by FdelMazo** [comment]
Lo ví! lo vi en la calle recién. Lo solucione hace unos minutos. Te fijas, por favor? Gracias @Maleriandro !

**Comment by Maleriandro** [comment]
Si, ahí funciona joya.
