### ISSUE TITLE
Nota de materias por equivalencia

### ISSUE THREAD

**Issue by nazar9318** [FdelMazo/FIUBA-Map#145]
Estaría bueno que para las materias que se agregan por equivalencia, además de agregar los créditos, se pueda agregar la nota y que ésta aporte al promedio.

**Comment by FdelMazo** [comment]
Hola @nazar9318 !

Estas seguro que las materias por equivalencia aportan al promedio y tienen nota? Yo nunca aprobé una, así que no me puedo fijar, pero la última vez que me fije en el SIU de una compañera vi que eso no pasaba, de la misma manera que no lo hacen los créditos por fuera del plan.

Yo aprobé algo4, que esta afuera de mi plan, y me dieron los créditos, pero la nota me fije y no influye en el promedio del siu.

Si tenés algun screenshot te lo agradezco!

**Comment by nazar9318** [comment]
Entiendo, ahora me confundí.
Pedí equivalencia por una materia de posgrado y para hacer la equivalencia
me pidieron la nota, de ahí que pensé que las notas cuentan.
Cuando me la acrediten me fijo si suben la nota o no.
Saludos y gracias.
