### ISSUE TITLE
Agregar créditos sueltos

### ISSUE THREAD

**Issue by franjuarez** [FdelMazo/FIUBA-Map#148]
Estaría bueno que se puedan agregar créditos sueltos.  Osea ganados de algún lado que no sean materias, como por ejemplo ser ayudante o participar en alguna competencia (a veces dan créditos)

**Comment by FdelMazo** [comment]
Hola Fran! Fijate que abajo a la izquierda, si pasas el mouse por los creditos, hay para agregar a manopla.

![image](https://user-images.githubusercontent.com/25667102/190043826-6f4fb578-dddc-4226-8bad-dda1c1656773.png)



Te sirve? Chifla!

**Comment by franjuarez** [comment]
Sii, no lo había visto. Hermoso!
