### ISSUE TITLE
Bug cuando se selecciona idioma

### ISSUE THREAD

**Issue by tomasaccini** [FdelMazo/FIUBA-Map#15]
El comportamiento cuando se pone idioma como aprobado es diferente al resto de las materias optativas: desaparece de la vista y solo aparece cuando se ocultan las optativas. Esto no pasa con las otras materias optativas, que incluso cuando las tenes aprobadas no aparecen cuando ocultas las optativas

https://user-images.githubusercontent.com/22566107/108907389-c9a45600-7600-11eb-8de6-89de1cc7e8ea.mp4

**Comment by FdelMazo** [comment]
Duplicado de #16 ! Solucionado en 8a7edfba9b0aa7262f68888687296151504a3bef !
