### ISSUE TITLE
Planes 2020 - Informática

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Map#153]
Aca esta el plan de informatica y la tabla de equivalencias (actuales, que probablemente cambie): https://mli-fiuba.notion.site/Ingenier-a-en-Inform-tica-48e3eeece07e471dbfe1cd947f7ca245

Estaría barbaro que cada persona pueda darse una idea de si le conviene o no pasarse de plan, viendo como le quedarían sus equivalencias.

Primero hay que agregar el plan, eso seguro. Pero despues, estaría barbaro agregar alguna manera de transformarse de informatica-1986 a informatica-2020 y que se complete todo solo

**Comment by FdelMazo** [comment]
Aca esta el plan de informatica y la tabla de equivalencias: https://mli-fiuba.notion.site/Ingenier-a-en-Inform-tica-48e3eeece07e471dbfe1cd947f7ca245

Tal vez antes de que arranque el cuatri que viene se puede hacer algun botoncito que sea un "fijate como quedarias en el plan 2020" que te muestre en base a tus datos actuales como te quedaria el nuevo?

**Comment by Maleriandro** [comment]
Subí un pull request agregando el nuevo plan de estudios. No estoy seguro como puedo hacer para asignar el pull request a este issue.

**Comment by FdelMazo** [comment]
Cerrado por #156
