### ISSUE TITLE
No se pueden guardar cambios en Plan 2020

### ISSUE THREAD

**Issue by Pablo1107** [FdelMazo/FIUBA-Map#159]
<img width="684" alt="image" src="https://github.com/FdelMazo/FIUBA-Map/assets/17091659/a309180c-e171-4a9b-b35d-898427ec9a25">

Como usuario hice un cambio a una materia (la puse en final y la cambie de cuatri de aprobacion) y el boton de guardado sigue disabled.

**Comment by FdelMazo** [comment]
Hola Pablo! Como el plan todavia no esta oficializado, deshabilite la opcion de guardar. Actualmente no se saben ni los códigos de las materias que se van a dar (lo cual es clave para mantener el estado de los usuarios). Asi que hasta que no haya algo oficial, voy a dejar todo en beta!

(y muchísimas gracias por los cafecitos!!!)

**Comment by Pablo1107** [comment]
Hola Federico. Tiene sentido igual está bueno dejar el issue abierto para cuando se solucione y la gente se encuentre con este problema sepa que todavía se esta trabajando.

¡Gracias a vos!

**Comment by FdelMazo** [comment]
Lo cierro y dejo pineado!
