### ISSUE TITLE
Las materias electivas a veces desaparecen cuando las clickeas.

### ISSUE THREAD

**Issue by nicomatex** [FdelMazo/FIUBA-Map#16]
![captured](https://user-images.githubusercontent.com/3434572/108908493-1fc5c900-7602-11eb-9324-53f8aea1d9b9.gif)

Para reproducir: 

1. Seleccionar Ingenieria en Informatica
2. Marcar todas las obligatorias como hechas
3. Clickear en "Materias electivas" para que aparezcan
4. Clickear en alguna materia electiva.

**Comment by nicomatex** [comment]
Probé varias veces, y no siempre desaparecen las mismas de la vista.

**Comment by FdelMazo** [comment]
TBH no entendi para nada por qué, pero 8a7edfba9b0aa7262f68888687296151504a3bef lo solucionó. Gracias por reportar!
