### ISSUE TITLE
Error en correlativa Materia Plan 2020 Informática

### ISSUE THREAD

**Issue by gabrieldiem** [FdelMazo/FIUBA-Map#160]
La materia _Gestión del desarrollo de Sistemas Informáticos_ del plan 2020 de Ingeniería en Informática tiene como única correlativa a _Ingeniería del Software I_ y debería tener como única correlativa a _Ingeniería del Software II_.

**Comment by FdelMazo** [comment]
@gabrieldiem perdoná, acabo de ver esto. Ojo que el notion dice que esta bien la correlativa!! Tenes alguna otra fuente del plan nuevo? 

https://mli-fiuba.notion.site/Ingenier-a-en-Inform-tica-48e3eeece07e471dbfe1cd947f7ca245

![image](https://github.com/FdelMazo/FIUBA-Map/assets/25667102/1aa59544-5983-44a4-bfdb-2db793fed833)

**Comment by gabrieldiem** [comment]
Ahhh, mirá. Me había fijado en el grafo que pedía Ingeniería del software II, pero en el borrador oficial está sólo Ingeniería del software I, así que seguramente el grafo quedó desactualizado. Así que está bien!
