### ISSUE TITLE
Créditos idioma Inglés en Plan 2020

### ISSUE THREAD

**Issue by camilofabregas** [FdelMazo/FIUBA-Map#165]
- Tener Inglés aprobada debería dar 4 créditos de electivas. Por lo que veo ahora mismo FIUBA Map no está contabilizando esos 4 créditos. Esto ya se confirmó en el grupo de WhatsApp del MLI Plan 2020.
- Marcar como completa la "Prueba de nivel de idioma inglés" no se guarda en la cuenta (según tengo entendido está desactivada la funcionalidad de guardar en el Plan 2020). En ese caso, creo que tenér aprobada Inglés en el plan viejo debería activarte automáticamente el casillero y además darte los 4 créditos.

**Comment by FdelMazo** [comment]
Hola @camilofabregas ! Actualmente no estoy haciendo mas cosas del fmap, al menos hasta que termine el cuatri. Pero no debería ser muy dificil de agregar lo que decis, si hacen un PR lo puedo revisar!

Eso sí, ojo que el plan viejo no registra que idioma aprobaste (usa la materia "idioma", en vez de "ingles"), entonces no estoy del todo seguro de si es correcto aprobar el nivel de ingles del plan nuevo (tal vez alguien curso frances!)

Es por eso que directamente removí todo lo que trata del idioma en la transicion. Mejor errar y sacarle 4 creditos a alguien, que hacerle creer que tiene 4 creditos mas de los que dice.

Como la transicion se va a revisar caso por caso para los estudiantes, lo que hay en el fiuba map es 100% tentativo y para darte una idea de como quedas en el plan nuevo, no intenta ser algo certero. Incluso, me parece que cuando se apruebe el plan directamente voy a remover la funcionalidad, asi fuerzo a todos a aprobar las materias una por una con lo que tengan en el SIU y sin equivocaciones

**Comment by FdelMazo** [comment]
Cierro este issue, que ya deje una aclaración de los planes nuevos en la app avisando que es algo tentativo y no 100% fiel a la realidad y porque actualmente no se puede hacer nada con inglés, porque el plan viejo no tiene registro de si se aprobó inglés u otro idioma.
