### ISSUE TITLE
Automatizar las actualizaciones a nuevos planes

### ISSUE THREAD

**Issue by salluzziluca** [FdelMazo/FIUBA-Map#167]
Se que el parseo siempre es medio polemico, pero por ahi se podria ver de que los .json se generan automaticamente en base a los PDFs de las diferentes carreras

**Comment by FdelMazo** [comment]
Hola @salluzziluca ! Si, es ideal, el mayor problema es que los PDFs en sí no suelen ser nada uniformes porque los escriben distintas comisiones. Mientras mas estandarizado este el upstream, mas sencillo es parsearlo. Por ahora no hay ningun plan nuevo que falta en la app, pero ojala los nuevos planes sean sencillos de parsear, cuando sean oficiales.

Si queres mandarte a hacer algun script (python? no se) que parsee pdfs y los pase al json que buscamos, bienvenido sea!

**Comment by FdelMazo** [comment]
Luca, cuando salgan los nuevos planes probablemente se necesite alguna forma copada de parsear los PDFs que vayan surgiendo. Estas invitadísimo a  ayudar con eso cuando pase! Cierro el issue hasta entonces, que los planes actuales ya están todos parseados
