### ISSUE TITLE
Voluntario

### ISSUE THREAD

**Issue by lopezac** [FdelMazo/FIUBA-Map#168]
Hola Fede, contribui al proyecto alla por marzo, y la verdad que es me parece muy copado y util el proyecto, me gustaria volverme un mantainer del proyecto, tengo conocimiento de React, Express y desarrollo web en general. Nos podemos comunicar con Telegram.

**Comment by FdelMazo** [comment]
Hola @lopezac ! 

Primero, muchas gracias por querer dar una mano, la verdad que lo aprecio mucho (y muchas gracias por la contribución de la vez pasada!).

En cuanto a la búsqueda de mantainers, me viene bárbaro ir sabiendo gente que este interesada en ayudar, por más que en este instante no haya tanto para hacer. 

La app (en mi opinión) está bastante estable. Mi mayor miedo con el fiuba map es que este año y el que viene seguramente empiecen a salir los planes 2020. Además de que salga un PDF oficial de la carrera (que hay que convertir en el json del fiuba map) el lío me parece que va a ser adaptar el código a las nuevas modalidades de las distintas carreras (quien sabe si son con orientaciones, si hay variabilidades en cuantos créditos dan las materias, etc). En este momento el fiuba map esta _muy_ hardcodeado a los planes que tiene, y esta poco flexible a cambios estructurales.

También esta el tema de que los planes nuevos requieren migraciones de los planes viejos, y todavía no estoy del todo decidido a si esas migraciones quiero que queden codeadas en el fiuba map (como ya pasa con ing informatica) o si quiero que cada usuario las cargue por su cuenta (como pasa con ing industrial) para que después no pueda echarle la culpa al fiuba map y decir "Che me dijiste que me tomabas física 2 como aprobada pero el SIU no me lo tomo y ahora no me puedo recibir".

Además del tema de los planes nuevos, siempre hay algunos issues abiertos o ideas dando vueltas de lo que se puede agregar. Si tenes algo que quieras aportar, o un issue del repo que quieras atajar, sentite libre de abrir un PR! En particular, me parece que #152 esta bueno y que toca el nucleo principal de la herramienta, es una buena forma de introducirse al código.

Por otro lado, la otra aplicación a la que eventualmente voy a dejar de darle bolilla es el organizador de horarios: https://github.com/FdelMazo/FIUBA-Plan/. En esa, el problema es que todos los cuatrimestres los horarios se tienen que actualizar frente a lo que hay en el SIU. En este momento ese proceso esta automatizado, pero depende de un servicio que provee fiuba (ofertahoraria.fi.uba.ar/), que nunca se sabe bien si fiuba misma sigue manteniendo o si va a morir. Mi miedo con el fiuba-plan es que eventualmente ese servicio muera, y la app deje de servir. Lo que quiero lograr es alguna manera de poder atajar eso, tal vez con una carga manual de horarios desde el SIU.

Después, obviamente, siempre existe la idea de hacer cosas más grandes. Integraciones para poder loginearte con tu cuenta del SIU, alguna manera de que lo que tenes guardado en el fiuba-map impacte en el fiuba-plan, etc etc etc. Ideas falopa siempre hay.

Pero como ya te digo.. es super preventiva mi búsqueda de mantainers, porque en este momento no creo que haya mucho para hacer! Para mi, lo primero y mejor que podes hacer es clavarle un `watch` al repo (o a los repos) para ir estando atento a issues nuevos que vayan surgiendo, y si alguno te gusta, siempre podes mandarte a codearlo. También esta bueno clonar el repo, levantarlo e intentar entender como funcionan cada uno de los componentes que tiene, que no son muchos.

Vos tenés alguna idea de algo que se pueda mejorar actualmente? Acepto cualquier tipo de contribución! Desde READMEs hasta upgrades de react hasta refactors de código feo.

Más allá de eso, sabe que en cualquier momento, podes hablarme a telegram sin problemas (vos, y quien lea este issue, obvio). Mi tg @fdelmazo.

(Este issue lo voy a dejar abierto, para que lo pueda ver cualquier otra persona que tenga la misma idea que vos)

(también, me parece que voy a actualizar un poco el cartel de búsqueda de mantainers del fiuba map, porque si no hay tanto laburo actual para hacer, no vale la pena tenerlo)

**Comment by FdelMazo** [comment]
Lo cierro y dejo pineado así no tengo un issue abierto de algo no accionable. Si a alguien le interesa ayudar, comente/reaccione/etc
