### ISSUE TITLE
Fix de correlativas (informatica 2020)

### ISSUE THREAD

**Issue by MaximoGismondi** [FdelMazo/FIUBA-Map#169]
No se si hay algunas correlativas que estan mal puestas pero me di cuenta que podía cursar Modelación numérica ya que según el borrador no depende de TDA. Y en el FIUBA-Map, Modelación numérica DEPENDE de TDA.

**Comment by FdelMazo** [comment]
Hola @MaximoGismondi. Todo lo que respecta al plan 2020 cambio mil veces, es imposible estar al día con las ultimas adiciones que se le hicieron. Si, tenés razón, en este momento el fmap esta desactualizado frente a lo último publicado del plan.

Yo estoy de vacaciones hasta que arranque el nuevo cuatri, no puedo darle la bolilla que requiere. Podes hacer un PR con los últimos cambios? Gracias!

Lo único que hay que hacer es modificar el archivo `informatica-2020.json`, confirmando que todo lo que esta ahí es vigente con lo último anunciado

**Comment by MaximoGismondi** [comment]
Consulta, de donde sacas los IDs para las materias ?? El último plan lo sacaron HOY según esta página: [Link](https://mli-fiuba.notion.site/Ingenier-a-en-Inform-tica-48e3eeece07e471dbfe1cd947f7ca245)

**Comment by FdelMazo** [comment]
@MaximoGismondi, los IDs de las otras carreras siempre estuvieron en los PDFs oficiales, pero por lo que averigüé, me contaron que los nuevos planes NO van a tener mas código de materia (lo cual arruina bastante al fiuba map, que depende mucho de un identificador para cada nodo).

Así que lo mejor va a ser inventar los nuevos IDs (yo pensaba algo así como las abreviaciones de las materias: `EBT1`, `AED`, `COMP`)

**Comment by amaruDuran** [comment]
Buenas! Perdón la intromisión. Quería avisar que las correlativas las estuve actualizando y otras cositas referidas al plan 2020 de informática que se subieron hoy a la madrugada en el notion del mli. Las dejé en este [PR](https://github.com/FdelMazo/FIUBA-Map/pull/170), para revisar sin apuro.

Saludos!

**Comment by MaximoGismondi** [comment]
Buenisimo! Saludos

**Comment by MaximoGismondi** [comment]
Buenisimo! Saludos
