### ISSUE TITLE
Limitar el des-zoom.

### ISSUE THREAD

**Issue by LucasDondo** [FdelMazo/FIUBA-Map#182]
¡Buenas Fede crack! Me imagino que a muchos nos gusta ir poco a poco subiendo la sensibilidad del _mouse_ hasta que cuando apenas lo acaricies ya dé 3 vueltas olímpicas a la pantalla.
El problema es que eso no es tan compatible con FIUBA Map todavía... (O más bien la sensibilidad de "la ruedita" del _mouse_) Porque al ampliar (bajar mucho el _zoom_) al final hasta perdes de vista el mapa. Estaría bueno que el _des-zoom_ solo te permita hacerlo hasta cierto punto (ponele, hasta el punto el cual ya se ven todas las materias).

https://github.com/FdelMazo/FIUBA-Map/assets/59975541/2b26c0ba-d243-4308-80f2-7c73d7b3df62

**Comment by FdelMazo** [comment]
Uh, la verdad que es una buena idea. Creo que visjs no tiene forma nativa de hacerlo, pero se puede hacer con un [listener al evento de zoom](https://stackoverflow.com/questions/49299774/how-to-limit-zooming-of-a-vis-js-network).  Esto se puede setupear en `createNetwork`.

Estaría bueno limitar tanto el zoom como el deszoom, y encontrarle algun valor sensible a cada uno.

Por otro lado, en tu video veo que el texto del CBC esta en negro, incluso en el dark mode. Eso no debería pasar! En que browser estas? Me sorprenden todos los colores de tu video, lo veo muy azulado. Tenes el contraste alto?

Así lo veo yo.
![image](https://github.com/FdelMazo/FIUBA-Map/assets/25667102/d76d0243-6668-4a8d-bbc7-bc6d3016e23b)

**Comment by LucasDondo** [comment]
> Estaría bueno limitar tanto el zoom como el deszoom, y encontrarle algun valor sensible a cada uno.

Banco!

> Por otro lado, en tu video veo que el texto del CBC esta en negro, incluso en el dark mode. Eso no debería pasar! En que browser estas? Me sorprenden todos los colores de tu video, lo veo muy azulado. Tenes el contraste alto?

Ah, no, es que uso [Dark Reader](https://darkreader.org). Jaja ahí lo desactivé para esa página. Buena observación!

**Comment by FdelMazo** [comment]
@LucasDondo, limite el zoom en 0f4a719115b00ff404e447024583876ab53be3f0

Queres testearlo en distintas carreras y si te parece bien implementado, cerrar el issue? Gracias!!

**Comment by LucasDondo** [comment]
Uh, nunca me llegó ninguna notificación ni nada... Vi que ya lo implementaste, ¡quedó joya! ¡Gracias Fede!
