### ISSUE TITLE
Registrar equivalencias directas de materias entre carreras

### ISSUE THREAD

**Issue by lazcanoluca** [FdelMazo/FIUBA-Map#186]
Se podrían registrar las materias que son equivalentes entre carreras (ej: 75.40 y 95.11, o sea, Algoritmos I, pero con códigos distintos en electrónica e informática), de forma tal que al ponerla en aprobada en una carrera, automáticamente aparezca como aprobada en otra carrera.

**Comment by lazcanoluca** [comment]
Me interesa trabajar en este issue, necesitaría nomás @FdelMazo un centro sobre cómo se registran las materias aprobadas en la bdd.

**Comment by lazcanoluca** [comment]
Estuve viendo y según entiendo en la bdd se guardan los mapas, indexados por carrera. O sea, para lograr mostrar las materias aprobadas (o puestas en cursada) por "equivalencia", habría que getear todos los mapas del usuario, luego para cada materia del mapa actual, ver cuáles son sus equivalentes, con esas, buscarlas a ver si está en alguno de los otros mapas del usuario, y con esa info crear un nodo para agregarlo a los demás...

**Comment by FdelMazo** [comment]
Hola @lazcanoluca, perdon que no te conteste antes... no te quiero pinchar el globo, pero esto es algo que no me gustaría agregar al fiuba map.

Siento que la superficie de error de un falso positivo es enorme, y que la contracara es obligar al usuario a tener que a mano marcar dos materias como aprobadas cuando aprueba una, lo cual no me parece tan grave.

Lo que mas quiero evitar en el fiuba map es adrede modificarle nodos al usuario. Con la transicion de plan viejo a plan nuevo lo intente hacer, y trajo muchos (muuuuchos) quilombos. En particular, las equivalencias (y las transiciones) es una lista que puede cambiar con el tiempo, lo cual requiere mas mantenimiento y tener que estar actualizado frente a las noticias de fiuba, y es algo que no sucede de inmediato en el SIU. 

Por ejemplo, uno de mis miedos es que alguien por ejemplo aprueba algo1 en informatica, se le registra automaticamente en electronica, y de la nada tiene mas de 140 creditos y se manda a cursar legal... solo que la algo1 de electronica todavia no la tiene en el SIU, entonces termina anotandose a una materia que no puede cursar.

Así, hay miles de cosas que pueden surgir de hacerle algo automaticamente al usuario sin que lo sepa, y prefiero evitarlo. Me gusta mantener la invariante del fiuba map de "tenes algo nuevo al siu, y a mano vas y lo cargas", en vez de dar falsas expectativas de que el fiuba map hace cosas por vos.

Que pensas? Disculpa y gracias por la idea!

**Comment by lazcanoluca** [comment]
Tiene todo el sentido del mundo el fundamento, te agradezco la respuesta detallada!
