### ISSUE TITLE
Script/herramienta para convertir csv/excel a json compatible

### ISSUE THREAD

**Issue by lazcanoluca** [FdelMazo/FIUBA-Map#188]
Si tenemos un script/tool así, sería menos tedioso crear los planes para las carreras. Podríamos pedirle a la gente de las otras carreras que nos pasen un excel con sus planes nuevos, y en un segundo generamos el json para agregarlo al fiubamap.

Abro el issue, capaz alguien tiene alguna idea.

PD: debe haber 500 "conversores" de csv a json, es cuestión de probar con algún excel y obtener un json compatible.

@FdelMazo esto puede ir como "buen first issue".

**Comment by FdelMazo** [comment]
El fiuba map arranco con eso! Le habia hecho un parser de pdfs que sirvio bastante para arrancar, cuando habia que llenar muchas carreras.

La idea de convertir automáticamente me encanta. El unico tema es que fiuba no tiene fuentes concisas (los planes nuevos son un... png, los viejos son pdfs no uniformes). Asi que hay que depender de que otros alumnos contribuyan su csv.

El tema de pedirle a alguien que te haga un excel y te lo pase es que.. la gente no aporta tanto como uno piensa. Tengo miedo de que alguien resuelva este issue, haga un conversor hermoso, y no pueda ser usado nunca y le haya hecho perder el tiempo al contribuidor. 

(Solo como nota, con un plan probamos la de pedirle a chatgpt "converti este notion en un json de este estilo" y anduvo bastante bien)

Por ultimo, cada vez faltan menos planes para agregar. Hoy solo faltan dos, y con el tiempo se van a agregar un par mas. No se si a veces conviene directamente hacer las cosas manuales en vez de [automatizarlas](https://xkcd.com/1319/), cuando son tan pocas.

---

Todo esto para decir: a mi particularmente automatizar los planes nuevos no me trae el valor que quiero, pero es cierto que es un gran first issue! Lo dejo abierto y si alguien tiene opiniones que se sume.

De ultima si queda muy stale lo cierro

**Comment by lazcanoluca** [comment]
Perfecto! Excelente el xkcd jajajaja

**Comment by FdelMazo** [comment]
Considerando que solo faltan muy pocos planes 2020 por llenar, y probablemente yo siga vivo para llenarlos manualmente, y despues por muchisimo tiempo no haya planes nuevos... cierro este issue, por miedo a que terminemos automatizando algo al cuete.
