### ISSUE TITLE
Cartel con créditos por materia

### ISSUE THREAD

**Issue by camiboj** [FdelMazo/FIUBA-Map#19]
La version anterior decia cuántos créditos asignaba una materia si apoyabas el mause

**Comment by FdelMazo** [comment]
En esta version no se puede, el port del network a react no lo soporta :(

Actualmente se puede ver, si estas loggeado, arriba a laderecha:

![image](https://user-images.githubusercontent.com/25667102/108926293-dfc00f80-761c-11eb-826d-72fc03bd0f09.png)
