### ISSUE TITLE
Cargar materias por cursar por Res 168/58

### ISSUE THREAD

**Issue by NicolasKorzusehec** [FdelMazo/FIUBA-Map#194]
Muy buen proyecto, la rompiste. Estaría bueno poder sumar materias de otros planes de ingeniería como si cursaras por Res 168/58. aunque sea manual, que pida toda la información. Caso de que le puedas poner si tiene equivalencia y si te cargan creditos extras de electivas.

**Comment by FdelMazo** [comment]
Hola @NicolasKorzusehec ! Gracias por la idea. Todo lo que es creditos manuales ya hay forma de hacerlo! esta documentado en #148.

Ademas de eso, tengo un issue abierto para quien quiera sumarse a intentar agregar codigo en #152 para que esas materias optativas funcionen como nodos extras del grafo, asi se les puede sumar la info que vos decis.

Tambien, como soy consciente de que el boton de creditos sueltos esta un poco escondido, tengo abierto #177 por si tenes alguna idea (o incluso algun PR) de donde ponerlo para que se vea bien.

Sentis que esto es mas o menos lo que pensabas, o que tenias en mente? Gracias!!

**Comment by NicolasKorzusehec** [comment]
Perfecto lo de #148, no lo había visto. Capaz el botón de "mas" directamente sobre la sección de créditos de electivas es mucho mas didáctico.
Recién vi el #152, me parece bien que por cada materia que agregues se cargue una burbuja violeta con el nombre de la materia y ahí le puedas asignar el estado de aprobación (sin tener que recurrir a asignar correlativas, ni nada).
En caso de que sean créditos sueltos con tal de que aparezca una burbuja blanca con contorno violeta que diga créditos adicionales y se vayan cargando es más que claro. 

Provisoriamente para simplificar esas materias y créditos extra, no estaría mal que haya una opción mas de agregar una bio que solo se lea cuando te paras sobre la materia y que las materias con un comentario así salgan con un contorno negro mas grueso o una solapita blanca marcada arriba a la derecha. Inclusive es interesante y para las del plan común.

Algunas de las aplicaciones que tendría como usuario:
Tenes la materia en final y te queres anotar hasta cuando la podes rendir y cuantos intentos te quedan
Escribir hasta cuando podes patear de cursarla sin que te afecte la cantidad de años, cualquier información de interés de la persona
Hay veces que alguna materia deja de dar algún tema que por ahí te interesa buscar en otro momento
Podes anotarte como cierre de materia todo lo que te quedo pendiente de hacer con esa materia, por mas de que aprobaste el final (Archivar el material antes de que te saquen del campus, buscar tal tema que no se dio en cursada o que dejaste en banda porque no te dieron los tiempos y te gustaría retomar, temas que te parecieron clave o que te gustaría profundizar de acá a algún futuro).

Que vos esos popup los puedas ver específicos sobre cada materia y agregar un botón mas que te abra un compilado de todos los que te armaste en un formato bien básico. Me parece que terminas sumándole muchas variables de como usar la aplicación como un notion general de tu carrera casi y sin caer en darle una gran complicación a la función, lo mas simple posible, un botón de comentario para las materias que solo se muestre cuando tocas la materia o cuando abrís todas tus anotaciones.

Te lo tiro como aporte obviamente, este proyecto es increíble, de fadu se mueren por algo así. Gracias por tomarte el tiempo de contestarme.

¿Cómo funciona la carga de materias y sus correlatividades?. No se que objetivo tenias con este proyecto (si algo social solo para la facu o algo mas general), capaz se puede armar una dinámica o funcionalidad que permita proponer un plan de tal carrera y tal facultad, que sea un apartado extra dentro del Map en el cual la persona cargue todas las materias y luego le vaya cargando como una función sobre cada materia las correlativas, al final que se cierre como un proyecto que te lo tire como un pullrequest y termine orientado todo a que hagas un chequeo sobre la información. Lo comento desde el desconocimiento de como funciona el sistema. Saludos

**Comment by FdelMazo** [comment]
Nico, gracias por los comentarios y las ideas, todo aporta.

Actualmente yo el proyecto lo estoy considerando casi casi terminado (faltan algunos planes 2020 que saldrán el año que viene), así que mucho código no le sigo agregando personalmente. Es difícil dar por concluido un proyecto, siempre hay una idea extra para meter... pero creo que el scope que tenia originalmente ya lo termina de cumplir: un organigrama y no mucho mas.

Eso sí, estoy hiper dispuesto a recibir código, pull requests e ideas y ver como incluirlas en el proyecto, así que gracias por tanto detalle. Siempre sirve algun voluntario (#168) que quiera meterle al repo!

> capaz se puede armar una dinámica o funcionalidad que permita proponer un plan de tal carrera y tal facultad

En cuanto a esto, sí, la idea es que como esto es código libre cualquier persona pueda clonar el repo y agregar su propia facultad. Ojala sirva. Actualmente no tengo ningún issue abierto donde se hable de como extender a otras facultades. Si querés, abrí uno y podemos ahí desglosar un poco mas los detalles de lo que implicaría, así al menos la siguiente persona que venga con una idea parecida tiene por donde arrancar

**Comment by FdelMazo** [comment]
Cerrado #177. El resto de las cosas se discute en los issues relevantes que quedan abiertos!
