### ISSUE TITLE
Facilitar el cambio de plan

### ISSUE THREAD

**Issue by frandelu** [FdelMazo/FIUBA-Map#196]
Ahora que estamos todos con el cambio de plan y hay algunas materia como ingles, que si las cursaste antes te dan los créditos o F1 y F2 que te dan física para informática + 12 créditos de electiva, estaría bueno poder cargar los créditos de electivas a mano o algo por el estilo para tener mas cómodo la cantidad de créditos que tenemos.

**Comment by FdelMazo** [comment]
Hola @frandelu gracias por la idea! Fijate que abajo a la izquierda hay un botoncito de sumar creditos, es lo que tenias en mente??

![image](https://github.com/FdelMazo/FIUBA-Map/assets/25667102/b934dc7d-ec54-42cc-bf73-09fd97d91c63)

**Comment by frandelu** [comment]
Si era eso, no lo encontraba.
