### ISSUE TITLE
Implement code formatter

### ISSUE THREAD

**Issue by lopezac** [FdelMazo/FIUBA-Map#201]
Hola, me parece un formateador de codigo serviria mucho para que el codigo quede mas ordenado y legible.

[Prettier](https://prettier.io/) me parece una muy buena opcion.

No sabria si harian falta alguna [set de rules](https://prettier.io/docs/en/options) o con las reglas por defecto esta bien.

Por ejemplo el archivo de body/Controls.js termina aumentadole 22 lineas, y para un archivo mas grande como Graph.js termina agregando 112 lineas, paso unos pastebin de body/Controls.js [sin prettier](https://pastebin.com/y4X5Tk2C), y [con prettier](https://pastebin.com/3jgiMRSa).

**Comment by FdelMazo** [comment]
Buenas! Me parece genial la idea. Prettier parece ser lo mas standard, y creo que por ahora es mejor salir sin set de reglas.

Gracias por el diff de con y sin prettier!

**Comment by lopezac** [comment]
Te parece bien que haga un pull request instalando prettier al proyecto y aplicandole prettier a todos los archivos del proyecto?.

**Comment by FdelMazo** [comment]
Si! Impecable. Gracias por la idea!

**Comment by lopezac** [comment]
Te pareceria bien instalar y aplicar prettier tambien en fiuba-repos y fiuba-plan?. @FdelMazo

**Comment by FdelMazo** [comment]
recontra! todo ayuda
