### ISSUE TITLE
Simplificar el final de carrera (Tesis / TPP)

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Map#209]
Originalmente tenemos lo de elegir entre tesis y tpp porque en informatica-1986 te daban distinta cantidad de creditos, así que era importante saber que elige el usuario.

los planes nuevos ya descartan esto y agregan el concepto de "Trabajo Integrador Final (TIF)" que es la misma cantidad de creditos para todo, así que se podemos directamente en los planes 2020 juntar las dos materias (Tesis/TPP) en un solo TIF y dejarlo como "final de carrera obligatorio" y listo

![image](https://github.com/FdelMazo/FIUBA-Map/assets/25667102/5cc39e0f-4387-46c3-b25d-c1acc9931979)

También es raro el concepto de "actividades profesionales", porque en los PDFs de las carreras dice que esto se integra directamente a el TIF. Tal vez hay que sacarlo directamente y listo.

(Esto solamente para los planes 2020, así no cambiamos para atras las cosas)

**Comment by lopezac** [comment]
@FdelMazo si entendi bien, vos decis entonces que en las carreras del plan 2020 habria que:

- Sacar lo de Tesis y TPP y dejarlo como Trabajo Integrador Final (TIF) ("final de carrera obligatorio")
- En los pdfs remplazar las 2 materias de TPP y Tesis por una materia de TIF, que sea del formato
`{`
  `"id": "TIF",`
  `"materia": "Trabajo Final Integrador",`
  `"creditos": 12,`
  `"correlativas": "...",`
  `"categoria": "Fin de Carrera"`
`},`
- En la barrita del footer sacar la parte de practica profesional de las 192 horas ya que el TIF implica que se hagan las 192 horas, me parece que el TIF y las 192 horas estan juntos

Me pierdo de algo?

**Comment by FdelMazo** [comment]
Si, es exactamente eso Alex! Creo que no se escapa nada
