### ISSUE TITLE
[BUG] Ingreso mi padron y se me pone la pantalla en negro

### ISSUE THREAD

**Issue by TomasSzeSirk** [FdelMazo/FIUBA-Map#212]
Ingreso mi padrón y me tira la pestaña en negro, probe con otros padrones y no pasa. Tambien probe con mi padrón en varios buscadores a ver si era eso y el resultado es el mismo

https://github.com/FdelMazo/FIUBA-Map/assets/86393038/80990d41-3f8c-416c-82bf-bb04b4fe70f5

**Comment by FdelMazo** [comment]
@TomasSzeSirk hola Tomi, querés probar ahora? Creo que lo arreglé en e44ba95d81f6d2bc3e28e864f2f2b812ddf91950

**Comment by TomasSzeSirk** [comment]
@FdelMazo ahí anda, mil gracias!
