### ISSUE TITLE
Agregar planes beta 2020 de mecanica y electricista

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Map#213]
Cuando el plan pase de estar en el micrositio a estar en la pagina de fiuba, deja de ser beta.

Hay que renombrar "ing electricista" a "ing en energia electrica"

- https://sites.google.com/fi.uba.ar/academica/nuevos-planes-de-estudio/plan-ing-mec%C3%A1nica/asignaturas-plan-mec%C3%A1nica

- https://sites.google.com/fi.uba.ar/academica/nuevos-planes-de-estudio/plan-ing-en-energ%C3%ADa-el%C3%A9ctrica/asignaturas-plan-el%C3%A9ctrica

**Comment by lopezac** [comment]
Hola @FdelMazo , lo implemento en un pull request y vos decis que te parece

**Comment by lopezac** [comment]
Ingenieria Electricista pasaria a ser Ingenieria Energia Electrica?
Osea quedarian entonces energia-electrica y energia-electrica-2020?

**Comment by FdelMazo** [comment]
Tal vez un mix? Los archivos los dejaria en "electricista" y "energia-electrica-2020", pero los nombres nuevos que sean "Ingeniería en Energía Electrica" y de corto un "Electricista". Total, son la misma carrera
