### ISSUE TITLE
Guardado del examen de suficiencia de Inglés

### ISSUE THREAD

**Issue by Taielmolina01** [FdelMazo/FIUBA-Map#215]
Buenas Fede, te levanto el issue porque noto hace rato que al guardar las materias con el examen aprobado al tiempo se borra. Te digo al tiempo se borra pero me suena raro que después de determinado tiempo automaticamente se borre, pero vos sabrás mas que yo como funciona. Ahi probé y pareciera que es cuando cambias entre planes de estudio/carrera como que se saca el tilde pero al tirar f5 aparece de nuevo (?, desconozco.

**Comment by FdelMazo** [comment]
Hola Tai!

Gracias por abrirme el issue. Que raro lo del tick, se deberia guardar junto a las materias siempre.  Tenes forma de replicar el caso en algun video y subirlo? 

Voy a chusmear hacer lo de cambiar de carrera a ver si me pasa lo mismo. Hoy por hoy si marcas cosas (materias, checks, lo que sea) y cambias de carrera sin tocar el botón de guardar antes, se pierden esos cambios. No se si eso lo cambiaría igual, me parece bien que haya que tocar el boton de guardar explícitamente.

**Comment by Taielmolina01** [comment]
Hola Fede, mira recien probando esta combinación ya se me desmarca, dudo que sea lo que realmente pasaba, pero bueno, bug aparte: marcas como completado el examen, guardas, cambias de carrera y/o plan de estudio, volves al plan "original" y te aparece desmarcado. Si tiras f5 te aparece marcado de nuevo pero creeria que ese comportamiento no está bueno.

No es lo que te habia comentado pero algun error similar debe haber dando vueltas, porque yo de inquieto entro seguido a la app (a ver si mirando fijo se me aprueba una materia sola) y ya te digo, estoy seguro que me paso de un dia dejar marcado y guardado, y volviendo a entrar me aparecía desmarcado. Insisto, desde la ignorancia, a mi tambien me parece raro pero bueno. Cuando tenga un rato de última me pongo a intentar romperlo a ver si encuentro realmente cuando pasa el bug.

**Comment by FdelMazo** [comment]
Gracias por verlo Tai. El bug estaba en como se guardan los datos del usuario localmente. Ya lo fixee: 53d780ee78b3855c539333789101ed1b826a3edb

Fijate si esta arreglado por favor!

**Comment by Taielmolina01** [comment]
Joya 10/10 ahora, te cierro el issue cualquier cosa si encuentro el bug original (capaz con esto ya está) lo vuelvo a abrir. Gracias:)
