### ISSUE TITLE
Visualizar oferta de materias

### ISSUE THREAD

**Issue by ptourne** [FdelMazo/FIUBA-Map#216]
Aunque el plan describe bastantes materias electivas, hay muchas que no se dan. Estaría bueno (tal vez conectandose a la base de datos de Fiuba Plan) mostrar qué electivas no están disponibles para cursar. Se podría cambiar el color o mostrar un simbolito dentro la cajita.

**Comment by FdelMazo** [comment]
Buenas! Gracias por el issue, me parece alta idea, pero no se me ocurre como implementarla. Hoy por hoy, FIUBA no te da los horarios de las materias (hace un cuatri que el fiuba plan dejo de mostrarlos tambien), entonces no se puede saber que materias actualmente estan en la oferta. 

Dejo abierto el issue por si a alguien se le ocurre como implementarlo.

**Comment by lopezac** [comment]
Hola Fede!, se podria quiza implementar una solucion similar a la de FIUBA-Plan, que si el usuario quiere ver las materias electivas que actualmente se estan dando en el cuatrimestre actual, cargue manualmente la oferta de comisiones de su siu guarani y con esa informacion (tendria que estar logueado) pueda ver cuales son las materias electivas que no se estan dando y darles otro color.

Que te parece?, mucho bardo quiza?, actualmente creo que no hay mucha mas solucion con las herramientas que proporciona FIUBA.

**Comment by FdelMazo** [comment]
Si, creo que eso ya se escapa bastante de la idea de que el fiuba map haga solo una cosa y bien. Para mí, como decís vos, todas las alternativas bloatean mucho la app. Me parece que no hay manera sencilla de meterlo :disappointed:
