### ISSUE TITLE
Incluir otras facultades

### ISSUE THREAD

**Issue by Maleriandro** [FdelMazo/FIUBA-Map#219]
Quería consultar que hay planeado respecto a planes para incluir carreras de otras facultades, o incluso otras universidades.
Tengo un par de amigos que ya me preguntaron respecto a si hay uno para su facultad, y siempre le tengo que decir que por ahora es solo para ingeniería.

Se aceptaría en esta misma página incluir otras facultades, o debería forkear para hacer uno propio?

**Comment by FdelMazo** [comment]
Buenas @Maleriandro! Planes míos para agregar facultades a este proyecto no hay. Es y siempre sera el FIUBA Map. Lo que si tiene es un par de forks de gente que agarro el core y lo aplico para su facultad: https://github.com/FdelMazo/FIUBA-Map/forks?include=active&page=1&period=&sort_by=stargazer_counts. Nunca me fije si la gente los usa mucho o no, no se cuanta mantención activa tendrán.

Adaptar el código a nuevas carreras o facultades no debería ser tan jodido porque cada carrera esta definida en su propio JSON, entonces mas allá de dos o tres porciones de código que hayan quedado mal hechas y quedaron muy especificas de FIUBA, debería ser extendible el concepto.

Estaría buenísimo hacer un UBA-Map, y meterle más facultades, pero la verdad es que la parte mas costosa es entender la carrera a modelar para poder pasarla a codigo. Justo en este momento FIUBA esta bastante estable por los planes nuevos, pero cada vez que salía una resolución nueva hay que estar muy encima para ver como se traduce a la herramienta, y como yo no soy de otras facultades siento que no me saldría hacer eso en otro lado.

Estas hiper bienvenido a forkear la app y hacer una de otra facultad!! Y si necesitas una mano con algo del código, siempre podes preguntarme acá o en otro issue.

**Comment by Maleriandro** [comment]
Buenisimo entonces, estuve revisando un poco como funciona, e incluso pude hacerle ingeniería inversa a la base de datos para ver como funcionaba tambien.
La unica cosa asi que no estoy muy seguro todavía es el tema del hosteo, que tengo que investigar si puedo conseguir alguno (preferentemente gratis, que por ahora solo estudio).
Cualquier duda que tenga supongo que te mando email, para no manchar este repo con issues no relacionados al desarrollo en este repo. Muchas gracias por el animo!
