### ISSUE TITLE
Electivas aprobadas pero no en verde

### ISSUE THREAD

**Issue by camiboj** [FdelMazo/FIUBA-Map#24]
Cuando ingreso mi padrón veo en la barra de abajo que tengo los créditos de mis materias electivas pero no figuran en verde ni con nota.
![image](https://user-images.githubusercontent.com/37842382/109009560-6f9da200-768d-11eb-9f56-fb464993335a.png)

Si selecciono una se actualiza la barra acorde a la image pero la imagen. Es decir, tanto en la barra como en el grafo sólo tengo aprobada la recien seleccionada.
![image](https://user-images.githubusercontent.com/37842382/109009711-9f4caa00-768d-11eb-88f9-9d6440c6c5fd.png)

**Comment by camiboj** [comment]
###Update
Si no estoy logeada e ingreso mi padrón funciona:
![image](https://user-images.githubusercontent.com/37842382/109023788-d88c1680-769b-11eb-9a7d-acf90852bf72.png)
Si le doy f5 o entro ya logeada es el error:
![image](https://user-images.githubusercontent.com/37842382/109023898-f0fc3100-769b-11eb-9eac-c2f600677331.png)

**Comment by FdelMazo** [comment]
Fixed en 75ec8e32f635ff8790b13accdd4f1e627ce6ee1c !

Venia muy de la mano con #16 , que arregle mal
