### ISSUE TITLE
Un botón para a abrir el cartel de sugerencias

### ISSUE THREAD

**Issue by camiboj** [FdelMazo/FIUBA-Map#28]
![image](https://user-images.githubusercontent.com/37842382/109165093-ebfdb700-7759-11eb-9de9-628087248e95.png)
Una vez que lo cerras no se puede volver a abrir salvo que le des f5.
Tal vez el botón de la carta (adjunto foto) es para eso, en todo caso no está funcionando.
![image](https://user-images.githubusercontent.com/37842382/109165204-0d5ea300-775a-11eb-9691-8a425ba2618d.png)

**Comment by FdelMazo** [comment]
Ademas de esto, tengo que agregar algun toast que avise que se envio el form ('Gracias!'), porque me estan clickeando 3 veces en send

**Comment by FdelMazo** [comment]
Más o menos mejorado en 03c81e8a1f2485eecb177dafb99f6d91965facfa (ahora hay feedback de que ya sugeriste algo, cuando se cierra el toast)

También, dentro de configuracion de usuario hay para mandar mas sugerencias.
