### ISSUE TITLE
Créditos fuera del plan

### ISSUE THREAD

**Issue by Lukas-De-Angelis-Riva** [FdelMazo/FIUBA-Map#29]
Se debería dejar poner créditos que conseguiste "fuera del plan" por ejemplo:
- Un  ingeniero no informático que hace la materia Organización de Datos, un ingenierio no industrial que hace Estadística aplicada I, II... etc: Por resolución 168.
- Una persona que hace los cursos de posgrado, por ejemplo: Aprendizaje estadístico.
- Créditos por pasantía

Ya que hoy día no hay forma de hacer valer estos créditos en la plataforma, y creo que se debería poder!!

**Comment by FdelMazo** [comment]
Me encanta la idea. Tengo que encontrar la mejor manera de implementarla (siempre acepto pull requests si querés codearla!). La dejo un poco en el backlog hasta terminar con los errores actuales de la pagina

**Comment by FdelMazo** [comment]
@Lukas-De-Angelis-Riva tenes idea de si esos créditos siempre aportan a la cantidad de créditos que se necesitan para materias electivas? Por ejemplo, siendo industrial y cursando Orga de Datos, tenes 6 créditos mas de materias electivas?

**Comment by Lukas-De-Angelis-Riva** [comment]
Efectivamente los créditos van a electivas. La cantidad de créditos que te dan por hacer una materia fuera del plan depende de la curricular, en general son 2 o 3.

**Comment by FdelMazo** [comment]
Joya. Sigo pensando donde encajarlo

**Comment by Lukas-De-Angelis-Riva** [comment]
Obviando la parte de que no soy diseñador gráfico (ni siquiera me acerco) se me había ocurrido que se haga con algo de este estilo:

![nuevo-boton](https://user-images.githubusercontent.com/60785752/110251434-27b92d80-7f5f-11eb-848a-87079e7e8c9a.png)

Donde abajo a la izquierda exista el botón para agregar más créditos
y que te abra la siguiente interfaz:
![nueva-ventana](https://user-images.githubusercontent.com/60785752/110251436-2ab41e00-7f5f-11eb-9eca-d17ac2aed368.png)

Donde puedas elegir por medio de los departamentos, si es algo posible, la materia que aprobaste y los créditos que la curricular te asignó.

Y luego si eso que aparezca volando por ahí la materia aprobada.

Las cuestiones a discutir serían:
1. ¿Debería ser una materia estática? ¿No la puedo aprobar ni desaprobar?
Lo que se podría hacer es que cuando le das a agregar créditos no lo hagas directamente sino que lo que estés haciendo es que en tu mapa aparezca una materia más para aprobar. (Podría cambiarse el nombre a "agregar materia", aunque interfiere con el tema de la pasantía).

2. ¿Cómo saco una materia que sin querer puse que aprobé?
Cuando la seleccionás podría darte la opción de quitarla del mapa.

Nunca hice web, así que no sé cuán difícil de implementar es lo que te estoy proponiendo, pero es algo así masomenos lo que me imaginaba.

**Comment by FdelMazo** [comment]
Claro, me gusta la idea, pero a nivel implementación romperia muuucho el poder agregar una materia al grafo (sería muy jodido que se guarden con los datos de cada persona, por ejemplo).  Por eso estoy intentando pensar en lo minimo necesario.

Lo esencial es poder sumar créditos de electivas, no? Todo el resto es decorado.

**Comment by FdelMazo** [comment]
A niveles enteramente practicos (todavia no codee nada ni pense el diseño de nada), que tán distinto a esto es lo que pensas necesario?

![image](https://user-images.githubusercontent.com/25667102/110255313-ce0e2e80-7f71-11eb-9922-781fb396faa0.png)

**Comment by Lukas-De-Angelis-Riva** [comment]
Me parece perfecto! Lo otro era, como decís vos, sólo decoración.

Con tener la posibilidad de agregarlo yo estoy muy conforme!

**Comment by FdelMazo** [comment]
Hola @Lukas-De-Angelis-Riva !

Ya agregue esta idea en 46d7c59076487b95f3bd25df5afa1ddacd53245b

- En electivas tenes para agregar creditos y motivo por los creditos
- Se guardan con tu usuario para la proxima vez que cargues
- Esos creditos (materias fuera del plan) no afectan al promedio
- Esos creditos solo aportan a la barrita de electivas

![image](https://user-images.githubusercontent.com/25667102/112765336-19e94c00-8fe3-11eb-8ac7-d61ebfc7baef.png)


Fijate si te gusta como quedó! Cerra el issue si te copó!

**Comment by Lukas-De-Angelis-Riva** [comment]
Está perfecto!!! Muchas gracias!!
