### ISSUE TITLE
Equivalencias

### ISSUE THREAD

**Issue by rodrisouto** [FdelMazo/FIUBA-Map#30]
En la migracion se ve que se perdieron todas las materias con el final aprobado pero sin nota.
Yo lo estaba usando asi para las materias que tengo aprobadas por equivalencias, estaria bueno agregar esa opcion en el dropdown de notas para las materias aprobadas, y que no cuenten (sumen al divisor) para el promedio.

**Comment by FdelMazo** [comment]
O sea, permitir aprobar con nota === 0? Y que aporte a la barra de creditos, pero no al promedio?

**Comment by FdelMazo** [comment]
Agregado ennnnnn e71c0ffa321350a05ebaa8fd7ce7609d7bb578f3
