### ISSUE TITLE
Estado "cursando" para materias

### ISSUE THREAD

**Issue by camiboj** [FdelMazo/FIUBA-Map#34]
Las materías podrían tener un estado básico (sin ningún tipo de información extra) como "en final"
Graficamente podría ser:
 1, naranja oscuro: representando que es una materia que se puede cursar que esta _seleccionada_ de alguna forma
 2. amarillo clarito: representando el paso anterior a "en final"

**Comment by camiboj** [comment]
personalmente vot 1.

**Comment by FdelMazo** [comment]
Agregado ennnnnn e71c0ffa321350a05ebaa8fd7ce7609d7bb578f3
