### ISSUE TITLE
No actualiza cuando se guarda por padron en distintas carreras

### ISSUE THREAD

**Issue by fmonpelat** [FdelMazo/FIUBA-Map#4]
Fede, como estas? veo que cuando se hace el load de las materias, no muestra la carrera correctamente. Te pregunto porque estoy haciendo electronica e informatica y al guardar con mi padrón en cada una solo me guarda una carrera.

```
 $('#clave-load').on('click', function () {
        let clave = $("#clave input").val();
        if (!clave) return;
        window.location = "https://fdelmazo.github.io/FIUBA-Map?clave=" + clave;
    });
```
window location no especifica la carrera, veo que con el save las guardas.

saludos, FM.

**Comment by FdelMazo** [comment]
Hola! La verdad que un alumno con dos carreras no fue un caso que contemple, porque haría que de alguna manera en load se tenga que resolver que carrera se quiere.

En el momento, el load agarra lo ultimo registrado por el usuario. Entonces si con tu padron guardas el progreso de electronica, y despues guardas el de informatica, pisas el registro de electronica, y cuando cargues se va a cargar solo el de informatica.

La solución actual sería guardar bajo dos claves distintas. Ponele guardar bajo 10000-elec y 10000-inf. No se me ocurre una forma comoda de hacer que se acepten distintas carreras en el cargado por el momento. ¿Se te ocurre algo?

**Comment by fmonpelat** [comment]
estas usando un spreadsheet de google como db?

**Comment by FdelMazo** [comment]
Si. La cuestion no es tema de guardar/cargar la carrera, si no de como presentarselo al usuario

**Comment by fmonpelat** [comment]
No, entiendo como presentarsela al usuario? si estas en la carrera seleccionada y pones refresh te debe cargar las materias de esa carrera, se podria pasarle a la pagina ademas del padrón la carrera y que te refresque materias de esa carrera. Debo leer un poco el codigo que hiciste ya que lo vi por arriba, despues reviso bien y te digo.

**Comment by FdelMazo** [comment]
Lo que me refiero es que con eso, lo que haces es que cada vez que entra un usuario de, por ejemplo, ing industrial, tiene que primero ir a esa carrera, y luego cargar sus datos. Me parece que forzaria un click de mas a los usuarios, y no es lo que busco. Me parece intuitivo cargar tu padron y que te lleve directamente a tu carrera/progreso, sin importar de donde partis

**Comment by fmonpelat** [comment]
ah, te entiendo. bueno se podria hacer asi, pones el padron le das a refresh te carga la primera carrera guardada, si hay otra te agrega un combo box debajo al lado de donde ingresaste el padron para poder elegir entre las 2 y le das refresh nuevamente si queres elegir la otra. no se si es bueno de esta manera, de ultima cerramos el issue jajajaja.

**Comment by FdelMazo** [comment]
Esta buena la idea, pero hay que tener en cuenta dos cosas. 

* Actualmente, se levanta (en load) el ultimo registro de la persona. Esto se hace 'server-side' en la DB, que hay un sheet con un filtro por fecha. Se tiene que modificar ese filtro para que sean "los ultimos registros de distintas carreras", que no es muy complejo

* Hay mucha gente que entra al sitio por primera vez, ve el input de padron, y guarda, porque si. Haciendo que por default varia gente empiece con el registro "Licenciatura en sistemas - solo aprobe el cbc" (el default). Habria que filtrar estos, no se si server side, o en guardar (algo asi como que si llamas al metodo save con el default, no se guarde), para evitar que un Químico entre a su cuenta y le salte un popup con su combobox con licenciatura.

Haciendo esas dos cosas, creo que es una buena idea!

Actualmente estoy trabajando en otros features/bugs del sitio, asi que no lo puedo desarrollar (y si se pone muy stale este issue, lo cierro). Pero las contribuciones son siempre (**siempre**) bienvenidas! Sea para esto, o para otras cosas.

**Comment by FdelMazo** [comment]
Solucionado en la nueva version!
