### ISSUE TITLE
Color del placeholder del textbox es parecido al color del background

### ISSUE THREAD

**Issue by jomedina96** [FdelMazo/FIUBA-Map#52]
Imagen de prueba:

![Untitled](https://user-images.githubusercontent.com/17090039/110224543-63022080-7ebb-11eb-8a31-73b6f6ea57a4.png)

**Comment by FdelMazo** [comment]
Gracias! Chusmeo como mejorarlo

**Comment by FdelMazo** [comment]
Lo voy a dejar así. En charka no hay manera comoda de cambiar el color del placeholder, y no se me ocurre otro color que no sea el gris para mostrar algo como temporario

**Comment by FdelMazo** [comment]
Lo termine cambiando por algo apeniiitas mas claro en 252985faaa0f8b110c71e3d3c9030c7219ee11ed

Gracias @jomedina96 por reportarlo!
