### ISSUE TITLE
Storing de materias cursando/cursadas a futuro

### ISSUE THREAD

**Issue by NachoRaik** [FdelMazo/FIUBA-Map#62]
Buenas Fede!
Por lo que vi, cuando seteas una materia con el feature de estarla cursando o que la vas a cursar en N cuatris, una vez que guardas y refresheas la pagina, se cargan como aprobadas (y nota 4).

Es algo que no sucede con las que estan como "Equivalencia" o "En Final", asi que imagino que es nomas que falto guardar un estado o algo del estilo.

Saludos!

**Comment by FdelMazo** [comment]
Fixeadoooo, alto caso borde. Gracias! No le estaba seteando la nota en desaprobada antes de ponerla en cursando, entonces si aprobas y despues pones en cursando, te la toma como aprobada

 a209822c84026826b8c7914cc6987633f065e31b
