### ISSUE TITLE
Conteo de créditos

### ISSUE THREAD

**Issue by nazar9318** [FdelMazo/FIUBA-Map#64]
Hice una prueba (en ingeniería informática) aprobándome muchas materias electivas, y en un momento conseguí completar el 100% de los créditos de la carrera.
Por lo que entiendo, el porcentaje no debería aumentar más si consigo superar el límite de créditos de materias electivas.
Saludos.

**Comment by FdelMazo** [comment]
Tengo que pensar alguna manera de implementarlo, pero si, esta mal

**Comment by FdelMazo** [comment]
(gracias por el issue!)

**Comment by nazar9318** [comment]
No vi el código, pero, ¿podrían hacerse listas de notas obligatorias/electivas/orientación, y que al recibir de la lista de electivas:
if (creditos_lista_electivas > creditos_electivas_pedidos) {return creditos_electivas_pedidos}?

**Comment by FdelMazo** [comment]
Sisi, pero mas alla del codigo, estoy pensando mas o menos cual seria la mejor manera de transmitirselo al usuario. Para mi lo ideal son las barritas de progreso por separado, pero la gente me pidio un contador 'global' como para darte una idea de como venis con la carrera en general.

El problema con esto es que si ese numero tiene esa cota por categoria, no va a estar bien mostrado en el circulito global (porque el porcentaje no va a ser clavado creditos/creditostotales). 

A mi, por mi parte, no me gusta para nada el circulo, lo sacaria del todo, pero bue

**Comment by FdelMazo** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/25667102/111907940-1af40980-8a36-11eb-9ac8-cb3971580e25.png">

Supongo que un circulito multiprogreso estaria bueno... pero pierde la idea de global. Me falta pensarlo un toque mas. Tal vez lo soluciono con porcentajes al lado de cada progressbar

**Comment by FdelMazo** [comment]
Supongo que se podria hacer algo asi... como un tag al lado de la barra de progresos, para que muestre que se refiere a eso el porcentaje

![image](https://user-images.githubusercontent.com/25667102/111916018-ceb9c100-8a57-11eb-943a-507e085cc135.png)

**Comment by FdelMazo** [comment]
![image](https://user-images.githubusercontent.com/25667102/111916238-b302ea80-8a58-11eb-8673-a9d71bae0f4b.png)

Este me va gustando más. Ideas?

**Comment by nazar9318** [comment]
Lo del contador global de la carrera se puede mostrar con la barra esa, el porcentaje es medio raro porque ¿cuánto porcentaje representa el total de las materias obligatorias? Es lo que marcás vos cuando decís: 
"El problema con esto es que si ese numero tiene esa cota por categoria, no va a estar bien mostrado, porque ya '100 de 300 creditos' no va a ser 33% si o si.. y confunde bastante eso"

Es como que habría que calcularle cierto peso a la cantidad de créditos de cada categoría (algo parecido a como hacían en Algo III para sacarte el promedio) pero no sabría de dónde sacar cada peso.

La barra con el tag me gusta. Haciéndolo en cada categoría sería menos confuso para saber el progreso.

Y para el contador global, se podría poner un contador de créditos totales y fue.

**Comment by FdelMazo** [comment]
Gracias nazar por  todo este seguimiento. Me estas ayudando una bocha. Que opinas de esto?

![image](https://user-images.githubusercontent.com/25667102/111923956-a4c8c480-8a80-11eb-88d5-43e478ef8a54.png)

- En vez de dar porcentaje de creditos, dejar el 'X de Y', y listo, que la gente se arregle dandose cuenta que no equivale 100% a cuan completa tenes la carrera.

- Si, sucede el issue original, si llenas todas las electivas del mundo, vas a tener '180 de 140' creditos, y no recibirte... peeeero, para eso lo aclaro con cada porcentaje por separado de cada barra de progreso (donde verias un '120%' en electivas.. y te darias cuenta que algo esta mal)

**Comment by FdelMazo** [comment]
Tambien se le puede poner un poco de amor... si pasas el 100% podes poner un gorrito, que se yo. Ideas para hacer mas amigable todo? (tambien decime que opinas del firulito al lado del promedio (que igual creo que se siente mas un link que otra cosa))


![image](https://user-images.githubusercontent.com/25667102/111924287-7b109d00-8a82-11eb-95e9-b2622de08d12.png)

**Comment by nazar9318** [comment]
Sí estoy de acuerdo que es mejor el "X de Y" créditos en cada categoría,
también podrías poner "X de Y créditos para la Tesis/TP" que ahí sí cuentan
el total de créditos que tengan.
Los gorritos me gustan, en caso de que alguno haga más materias electivas
que las pedidas se podría poner algún ícono más, tipo el emoji del nerd o
algo así.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by FdelMazo** [comment]
Fixeado todo en 0d67ae7a99a9121be4a1d718ec25c7a8cb425a93

Gracias por las sugerencias!!!

**Comment by nazar9318** [comment]
Excelente, me encantó cómo quedó.
Saludos!
