### ISSUE TITLE
Agrupaciones de créditos

### ISSUE THREAD

**Issue by nazar9318** [FdelMazo/FIUBA-Map#65]
El map sólo muestra los créditos de las obligatorias y electivas, los créditos de la orientación los cuenta como electivas. Sería bueno que se de una opción de elegir una orientación en el map para que las diferencie, las demás orientaciones cuenten como electivas y que si no se elige ninguna (que puede pasar hasta que uno elija entre tésis o TP), las vaya contando como electivas.
Saludos.

**Comment by nazar9318** [comment]
Hasta se me ocurrió que se podrían agregar más barras de porcentajes:
Barra de obligatorias, de electivas, de orientación, y total.

**Comment by FdelMazo** [comment]
Todo eso existe, una vez que te loggeas con tu padron* y elegis tu orientacion y final de carrera.

![image](https://user-images.githubusercontent.com/25667102/111868632-d430e180-8959-11eb-94dd-098da606e25e.png)

Arriba a la izquierda tengo mi 'menu de configuracion' donde marco esas opciones, y la barra de abajo se adapta a esas decisiones.

* Esto no es de mala leche y de 'registrate para las features premium', es porque si entras sin loggearte, estas queriendo probar cosas rapido, y no te importa persistir la informacion, solo queres saber que queres cursar el cuatri que viene. En cambio, si entras loggeado, te importa mantener registro de tus notas, creditos, final de carrera, etc.

**Comment by nazar9318** [comment]
Excelente, no sabía que eso existía. Me había loggeado con el padrón pero sólo vi la opción de guardar el progreso, de las demás features no sabía. 
Ahí cierro el issue, felicidades por tu trabajo.
Saludos.
