### ISSUE TITLE
No persiste la información de materias

### ISSUE THREAD

**Issue by pastelito-de-limon** [FdelMazo/FIUBA-Map#66]
### Contexto 
Vengo usando el mapa de antes de esta última gran actualización y nunca tuve ningún problema. Tengo mi perfil guardado con mi padrón.

### Lo que sucedió
Noté que en tres materias no figuraban mis datos previamente cargados de otro día (dos aprobadas y una cursando). A pesar de intentar reescribir la info de las mismas y apretar guardar (probé con o sin autosave), luego de cerrar sesión, actualizar la página y reingresar, los cambios se esfuman. Tampoco se guarda mi configuración de "marcar como completo" en la prueba de nivel de idioma inglés.

### Lo que esperaba que suceda
Deberían haberse guardado mis datos en mi perfil, cosa de poder cerrar y reabrir sesión y verlos allí.

### Aclaraciones
Por las dudas, comento que las materias que menciono son todas obligatorias de la carrera de Licenciatura en Informática. Estoy usando Mozilla Firefox 86.0.1 (64-bit), que es la versión más actualizada. Es el primer issue que creo, así que si hice algo mal, que alguien me avise, por favor.

**Comment by FdelMazo** [comment]
Gracias por el issue. Me ayudas a replicarlo?

Decime tu padron, que tengo que marcar como aprobado y me fijo que esta pasando!

**Comment by pastelito-de-limon** [comment]
Es extraño, porque ahora estaba intentando nuevamente y sí me aparecen todos los datos... No sé si modificaste algo o qué habrá pasado, porque ahora todo pareciera guardarse normalmente :/ Disculpame si creé el issue innecesariamente, pero por mi parte sentite libre de cerrarlo.

**Comment by FdelMazo** [comment]
Estuve tocando un par de cosas de como se accede a la base de datos en aae7b667b570001712544318566d5bd8e6fc48f7

Tranquilamente se soluciono ahí! 

Cualquier otra cosa, reabri este issue o abrime otro. Abrazo!
