### ISSUE TITLE
Bug cargar materias

### ISSUE THREAD

**Issue by camiboj** [FdelMazo/FIUBA-Map#70]
Entre y habian desaparecido muchas de mis materias aprobadas:
![image](https://user-images.githubusercontent.com/37842382/111687662-4e058580-8809-11eb-86d6-ca98b4d9d713.png)

Me desloge y me volvi a logear:
![image](https://user-images.githubusercontent.com/37842382/111687719-5eb5fb80-8809-11eb-80f9-365c7bbc8811.png)
(desde aca si le doy F5 vuelvo a la primer imagen)

**Comment by camiboj** [comment]
FYI: la ultima actualización que hice fue aprobar ingles. Tal vez eso tenga que ver

**Comment by FdelMazo** [comment]
rarisiimoooooo. ahi lo chusmeo

**Comment by camiboj** [comment]
Also, notar que cuando sí me aprece bien las notas igualmente falta ingles

**Comment by FdelMazo** [comment]
Lo probas ahora? Debería estar funcionando con ea32a811071d729eb5ccee9d5033f8212f126ece

**Comment by camiboj** [comment]
Funciona de 10

**Comment by FdelMazo** [comment]
Geniallllll
