### ISSUE TITLE
Detalle visual en las secciones con 0%

### ISSUE THREAD

**Issue by julianferres** [FdelMazo/FIUBA-Map#72]
Cuando la tesis no esta hecha, en lugar de marcar 0% muestra un rectangulo vacio.

**Comment by FdelMazo** [comment]
Gracias Juli! Lo deje así por diseño, porque la tesis no tiene progreso, es o la tenes aprobada o no, entonces supuse que es mejor que parezca mas como un booleano/toggle, que como un 0%

Si se te ocurre una manera mas comoda de mostrar eso, contame!

**Comment by FdelMazo** [comment]
Es por eso que el 100% es un sombrerito en vez de un 100%

**Comment by julianferres** [comment]
Buenísimo Fede! Tiene todo el sentido.
