### ISSUE TITLE
Error desde el navegador para celular

### ISSUE THREAD

**Issue by FrancoPrime** [FdelMazo/FIUBA-Map#78]
Cuando se toca una materia para darla como aprobada, si en ese momento se toca en la parte desde la mitad de la pantalla hacia la derecha se cambia de carrera(según la altura). Tal vez hay algún panel invisible. Pasa solo desde el celular o desde la computadora emulando un celular.
![error](https://user-images.githubusercontent.com/21978872/114786768-141a9700-9d55-11eb-8514-791e58e49559.gif)

**Comment by FdelMazo** [comment]
Muchas gracias por el video Franco! Cuando me ponga a probarlo te cuento que encontré

**Comment by FdelMazo** [comment]
La verdad es que todo lo que es mobile no le di mucho support, porque es una aplicacion mucho mas de escritorio. Pero si tenes sugerencias de como hacer que sea mas lindo para celulares, escucho ideas!

**Comment by FdelMazo** [comment]
@FrancoPrime fixeado en 14df0f8ea4970b10e8a2b01a53d971d1824860de
Si te cruzas otros errores en mobile, levanta el issue tranqui! Gracias!!
