### ISSUE TITLE
Reseteo de posiciones al marcar como aprobada

### ISSUE THREAD

**Issue by AlePaff** [FdelMazo/FIUBA-Map#79]
Si desplazas una materia hacia arriba o hacia abajo y luego le poner como aprobada se resetean todas las posiciones.

![dd](https://user-images.githubusercontent.com/43119891/115273163-9ae4c080-a115-11eb-9df7-f94afde6e42b.gif)

**Comment by FdelMazo** [comment]
Hola Ale! Gracias por marcarme esto. El tema de las posiciones de los nodos es que son fijos, porque el mapa no tiene las 'fisicas' (lo que hacia que reboten en la version anterior, por ejemplo) prendida, porque trae muchos problemas de performance.

Por ahora no tengo una buena solucion para este tema, pero creo que de #80 puede salir algo copado. Si puedo arreglarlo lo arreglo, pero por ahora no tengo idea como! 

(Muchas gracias por el video! Los issues son mucho mas cómodos de entender asi)

**Comment by FdelMazo** [comment]
Despues de mucha piña y error, no pude solucioanr esto. Si o si habría que recuperar la fisica del mapa, que es algo que es un re quilombo y prefiero no hacer (aunque se puede laburar un toque sobre `Physics`, que esta casi terminado). Lo cierro
