### ISSUE TITLE
Créditos por pedido (Ayudantías, Trabajos en laboratorios,  Intercambios, etc...)

### ISSUE THREAD

**Issue by frossi-fiuba** [FdelMazo/FIUBA-Map#81]
Buenas! Dejo esto por acá para pensarlo... Creo que estaría bueno agregar un "extra credits" o algo así para los casos en los cuales se obtienen créditos de manera indirecta como ayudantías, intercambios a otras universidad, etc. No me parece que tenga que ser una materia en particular si no una opción que agregue créditos a optativas directamente y puedas agregar esos créditos para realizar un mejor seguimiento de la carrera, pues tengo entendido que esto tampoco afecta al promedio. Si es que ya están y no los encontré pido mildis... 

Slds.

F.

**Comment by FdelMazo** [comment]
Hola Frossi! Gracias por la idea, pero te ganaron de mano en #29 !

Esta idea ya la agregue! Chusmeate mi comentario en: https://github.com/FdelMazo/FIUBA-Map/issues/29#issuecomment-808947233

Cualquier cosa reabrime el issue! Gracias!
