### ISSUE TITLE
Agregar opcion de marcar optativas como "Quiero cursar"

### ISSUE THREAD

**Issue by Maleriandro** [FdelMazo/FIUBA-Map#87]
Estaría buena la opción de poder marcar a las optativas como materias que se "quieren cursar", y que eso automáticamente te marque todas las optativas necesarias para cursar esa, e inclusive tal vez, que te indique cuantos créditos obtendrías por completar todas las optativas para llegar a esa que uno desea cursar.

**Comment by FdelMazo** [comment]
Hola @Maleriandro ! Me suena un toque complejo el feature, creo que ya se cubre bastante con el feature de 'a cursar en N cuatrimestres', lo usaste? Fijate si te sirve, y si te parece muy distinto intento pensar alguna manera de implementar esto, pero no estoy del todo seguro de que me cope

**Comment by FdelMazo** [comment]
Tal vez si lo convences, @JDSanto te lo codea

**Comment by Maleriandro** [comment]
Claro, si, ni que estaba esa opción, no es exactamente lo que decía yo, pero se acerca lo suficiente. No sé que tan complicado sería agregarle a ese "cursas en N cuatrimestres" para que te indique abajo la cantidad de créditos que conseguirías con esas materias.

**Comment by FdelMazo** [comment]
@Maleriandro estuve un buen rato intentando implementar algo de este estilo, pero la verdad que no pude, ni me convencieron los resultados. Me gusta mucho la idea de saber cuantos creditos vas a agregar a medida que avancen los cuatris que marcaste a cursar, pero no tengo manera comoda de hacerlo. Cierro el issue!
