### ISSUE TITLE
Actualizacion del Plan de Estudio

### ISSUE THREAD

**Issue by LucasWaisten** [FdelMazo/FIUBA-Map#97]
Hola! Te queria comentar que este primer cuatrimestre del 2021 se aprobo el nuevo plan de estudio de la carrera Ingeneria Informatica. 

Te lo queria pasar para que veas y puedas actualizar las corrrelatividades de las materias en ese carrera! 
[20210430_plan_aprobado.pdf](https://github.com/FdelMazo/FIUBA-Map/files/6888023/20210430_plan_aprobado.pdf)

**Comment by FdelMazo** [comment]
Hola Lucas! La actualización ya esta implementada! Se hizo en #86 

Cuando entras a la carrera de ing informatica esta plasmado. Hay alguna materia que veas mal?

**Comment by LucasWaisten** [comment]
Hola Fede! Despues de mandar el mensaje me di cuenta que tenian actualizado jaja. Mil disculpas.

El mapa esta muy bueno!

**Comment by FdelMazo** [comment]
Genial!
