### ISSUE TITLE
Sugerencia FIUBA Map

### ISSUE THREAD

**Issue by BautistaRodriguez** [FdelMazo/FIUBA-Map#98]
Tengo una sugerencia. Si es que no esta y no lo encontre...
Me pareceria copado que te vaya calculando los creditos de electivas que tenes y/o que te faltan. Ya que con el nuevo cambio del plan de ingenieria informatica se perdio un poco la nocion de ello.

**Comment by FdelMazo** [comment]
Hola Bautista! Actualmente, __solo si estas loggeado__ (es decir, si pones una clave o padron en el firulito de arriba a la izquierda), te va a aparecer abajo una barra de progreso donde podes ver los creditos que tenes.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/25667102/129247745-adfd5e16-1204-48d6-8bdf-b1ca3a1fde1c.png">

Decias algo asi, o que estabas pensando?

**Comment by FdelMazo** [comment]
Cierro el issue hasta que haya respuesta de @BautistaRodriguez , porque ya esta implementado
